#pragma checksum "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0e873c67862b809450d949f99942561ac0ef1997"
// <auto-generated/>
#pragma warning disable 1591
namespace Razor
{
    #line hidden
#nullable restore
#line 1 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\_ViewImports.cshtml"
using HDKmall;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\_ViewImports.cshtml"
using HDKmall.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\_ViewImports.cshtml"
using HDKmall.ViewModels;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\_ViewImports.cshtml"
using HDKmall.Helpers;

#line default
#line hidden
#nullable disable
    public class Template
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 1 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
Write(model);

#line default
#line hidden
#nullable disable
            WriteLiteral(" ProductDetailVM\r\n\r\n");
#nullable restore
#line 3 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
  
    ViewData["Title"] = Model.Name;
    ViewData["MetaDescription"] = Model.Description?.Length > 160 ? Model.Description.Substring(0, 157) + "..." : Model.Description;
    
    // Default version is the first one
    var defaultVersion = Model.Versions.FirstOrDefault();
    ViewData["OgImage"] = defaultVersion?.ImageUrl ?? Model.ImageUrl;

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
<style>
    :root {
        --primary-red: #d70018;
        --soft-bg: #f4f6f8;
        --card-shadow: 0 1px 6px rgba(0,0,0,.08);
    }

    .pd-section { background: var(--soft-bg); padding: 24px 0 60px; }
    .glass-card { background: #fff; border-radius: 16px; box-shadow: var(--card-shadow); border: none; }
    
    /* Version & Variant Selectors */
    .selector-label { font-size: 14px; font-weight: 700; color: #444; margin-bottom: 12px; display: block; }
    .option-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(110px, 1fr)); gap: 10px; margin-bottom: 24px; }
    
    .option-item {
        border: 1.5px solid #e0e0e0;
        border-radius: 10px;
        padding: 10px;
        cursor: pointer;
        transition: all 0.2s ease;
        background: #fff;
        text-align: center;
        display: flex;
        flex-direction: column;
        justify-content: center;
        min-height: 56px;
    }
    .option-item:hover { border-color: var(--primary-r");
            WriteLiteral(@"ed); background: #fff5f5; }
    .option-item.active { border-color: var(--primary-red); background: #fff5f5; box-shadow: 0 0 0 1px var(--primary-red); }
    .option-name { font-size: 13px; font-weight: 700; color: #333; display: block; }
    .option-price { font-size: 11px; color: #666; margin-top: 2px; }
    
    /* Price display */
    .price-container { background: #fff5f5; border-radius: 12px; padding: 20px; margin-bottom: 24px; }
    .current-price { color: var(--primary-red); font-size: 2.2rem; font-weight: 800; line-height: 1; }
    
    /* Gallery */
    .gallery-main-wrapper { position: relative; padding: 20px; background: #fff; border-radius: 16px; margin-bottom: 15px; cursor: zoom-in; }
    .gallery-main { width: 100%; aspect-ratio: 1/1; object-fit: contain; }
    .thumb-scroll { display: flex; gap: 10px; overflow-x: auto; padding-bottom: 10px; justify-content: center; }
    .thumb-item { width: 60px; height: 60px; border-radius: 8px; border: 2px solid #eee; cursor: pointer; object-fit");
            WriteLiteral(@": cover; transition: .2s; }
    .thumb-item.active { border-color: var(--primary-red); }

    /* Action Buttons */
    .btn-action-group { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 20px; }
    .btn-buy-now { background: var(--primary-red); color: #fff; border: none; border-radius: 12px; padding: 16px; font-weight: 700; transition: .2s; }
    .btn-buy-now:hover { background: #b5000f; transform: translateY(-2px); }
    .btn-cart-outline { background: #fff; color: var(--primary-red); border: 2px solid var(--primary-red); border-radius: 12px; padding: 16px; font-weight: 700; transition: .2s; }
    .btn-cart-outline:hover { background: var(--primary-red); color: #fff; transform: translateY(-2px); }

    /* Tabs-like sections */
    .section-title { font-size: 18px; font-weight: 800; color: #333; margin-bottom: 20px; padding-bottom: 10px; border-bottom: 2px solid #f0f0f0; position: relative; }
    .section-title::after { content: ''; position: absolute; bottom: -2px; left:");
            WriteLiteral(@" 0; width: 60px; height: 2px; background: var(--primary-red); }
</style>

<div class=""pd-section"">
    <div class=""container"">
        <!-- Breadcrumb -->
        <nav class=""mb-4 small"">
            <a href=""/"" class=""text-muted text-decoration-none"">Trang chủ</a>
            <span class=""mx-2"">/</span>
            <a href=""/Product"" class=""text-muted text-decoration-none"">Điện thoại</a>
");
#nullable restore
#line 74 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
             if (Model.Category != null) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                <span class=\"mx-2\">/</span>\r\n                <a");
            BeginWriteAttribute("href", " href=\"", 3962, "\"", 4006, 2);
            WriteAttributeValue("", 3969, "/Product?categoryId=", 3969, 20, true);
#nullable restore
#line 76 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 3989, Model.CategoryId, 3989, 17, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" class=\"text-muted text-decoration-none\">");
#nullable restore
#line 76 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                                   Write(Model.Category.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</a>\r\n");
#nullable restore
#line 77 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
            }

#line default
#line hidden
#nullable disable
            WriteLiteral("            <span class=\"mx-2\">/</span>\r\n            <span class=\"fw-bold text-dark\">");
#nullable restore
#line 79 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                       Write(Model.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</span>
        </nav>

        <div class=""row gx-4"">
            <!-- Image Column -->
            <div class=""col-lg-5 mb-4"">
                <div class=""glass-card p-2"">
                    <div class=""gallery-main-wrapper"" onclick=""openZoomModal()"">
                        <img id=""mainDisplayImg""");
            BeginWriteAttribute("src", " src=\"", 4496, "\"", 4577, 1);
#nullable restore
#line 87 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 4502, defaultVersion?.ImageUrl ?? Model.ImageUrl ?? "/img/Product_Default.jpg", 4502, 75, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" class=""gallery-main"" />
                    </div>
                    <div class=""thumb-scroll"" id=""galleryThumbs"">
                        <!-- Thumbs will be injected by JS based on selected version -->
                    </div>
                </div>
            </div>

            <!-- Content Column -->
            <div class=""col-lg-7"">
                <div class=""glass-card p-4 h-100"">
                    <h1 class=""fw-bolder mb-3 fs-3"">");
#nullable restore
#line 98 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                               Write(Model.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h1>\r\n                    \r\n                    <div class=\"d-flex align-items-center gap-3 mb-4\">\r\n");
#nullable restore
#line 101 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                         if (Model.Brand != null) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                            <span class=\"badge bg-light text-secondary border\">");
#nullable restore
#line 102 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                          Write(Model.Brand.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</span>\r\n");
#nullable restore
#line 103 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                        }

#line default
#line hidden
#nullable disable
            WriteLiteral("                    </div>\r\n\r\n                    <!-- Versions (Capacities) -->\r\n                    <span class=\"selector-label\">Chọn dung lượng</span>\r\n                    <div class=\"option-grid\">\r\n");
#nullable restore
#line 109 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                         foreach (var v in Model.Versions)
                        {
                            bool isActive = v.Id == (int)(ViewBag.ActiveVersionId ?? 0);

#line default
#line hidden
#nullable disable
            WriteLiteral("                            <div");
            BeginWriteAttribute("class", " class=\"", 5748, "\"", 5795, 2);
            WriteAttributeValue("", 5756, "option-item", 5756, 11, true);
#nullable restore
#line 112 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue(" ", 5767, isActive ? "active" : "", 5768, 27, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            BeginWriteAttribute("onclick", " \r\n                                 onclick=\"", 5796, "\"", 5859, 3);
            WriteAttributeValue("", 5841, "goToVersion(", 5841, 12, true);
#nullable restore
#line 113 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 5853, v.Id, 5853, 5, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 5858, ")", 5858, 1, true);
            EndWriteAttribute();
            WriteLiteral(" \r\n                                 data-version-id=\"");
#nullable restore
#line 114 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                             Write(v.Id);

#line default
#line hidden
#nullable disable
            WriteLiteral("\">\r\n                                <span class=\"option-name\">");
#nullable restore
#line 115 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                     Write(v.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</span>\r\n                                <div class=\"d-flex flex-column align-items-end\">\r\n                                    <span class=\"option-price\">");
#nullable restore
#line 117 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                          Write(v.BasePrice.ToString("N0"));

#line default
#line hidden
#nullable disable
            WriteLiteral("₫</span>\r\n");
#nullable restore
#line 118 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                     if (v.DiscountPercent > 0)
                                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                        <span class=\"badge bg-danger rounded-pill py-0\" style=\"font-size: 10px;\">-");
#nullable restore
#line 120 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                                              Write(v.DiscountPercent);

#line default
#line hidden
#nullable disable
            WriteLiteral("%</span>\r\n");
#nullable restore
#line 121 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                    }

#line default
#line hidden
#nullable disable
            WriteLiteral("                                </div>\r\n                            </div>\r\n");
#nullable restore
#line 124 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                        }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                    </div>

                    <!-- Variants (Colors) -->
                    <span class=""selector-label"">Chọn màu sắc</span>
                    <div class=""option-grid"" id=""colorSelector"">
                        <!-- Colors injected by JS -->
                    </div>

                    <!-- Price -->
                    <div class=""price-container"">
                        <div class=""d-flex align-items-center gap-3"">
                            <div class=""current-price"" id=""activePrice"">--</div>
                            <div id=""activeOriginalPrice"" class=""text-muted text-decoration-line-through fs-5"" style=""display:none;""></div>
                            <span id=""activeDiscountBadge"" class=""badge bg-danger fs-6"" style=""display:none;""></span>
                        </div>
                        <div class=""mt-2 small text-muted""><i class=""bi bi-truck me-1""></i> Miễn phí giao hàng toàn quốc</div>
                    </div>

                    <div class=""bt");
            WriteLiteral(@"n-action-group"">
                        <button class=""btn-buy-now"" onclick=""handleBuyNow()"">MUA NGAY</button>
                        <button class=""btn-cart-outline"" onclick=""handleAddToCart()"">THÊM VÀO GIỎ</button>
                    </div>

                    <div class=""p-3 rounded-3 border bg-light small text-muted"">
                        <div class=""d-flex gap-2 mb-2""><i class=""bi bi-shield-check text-success""></i> Bảo hành 12 tháng chính hãng</div>
                        <div class=""d-flex gap-2""><i class=""bi bi-arrow-repeat text-success""></i> Đổi trả trong 30 ngày nếu có lỗi</div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Details Row -->
        <div class=""row mt-4 gx-4"">
            <!-- Left: Description + Specs -->
            <div class=""col-lg-8"">
                <!-- Description -->
                <div class=""glass-card p-4 mb-4"">
                    <h2 class=""section-title"">Thông tin sản phẩm</h2>
            ");
            WriteLiteral(@"        <div id=""versionDescription"" class=""text-muted"" style=""white-space: pre-wrap;"">Đang cập nhật...</div>
                </div>
                <!-- Specifications -->
                <div class=""glass-card p-4 mb-4"">
                    <h2 class=""section-title"">Thông số kỹ thuật</h2>
                    <div id=""specContainer"">
                        <p class=""text-muted"">Đang cập nhật...</p>
                    </div>
                </div>
                <!-- Reviews (CellphoneS Style) -->
");
#nullable restore
#line 173 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                  
                    var existingReview = ViewBag.UserExistingReview as HDKmall.Models.Review;
                    var canReview = ViewBag.CanReview == true;
                    var hasBought = ViewBag.HasBought == true;
                    var defaultVersionId = (int)(ViewBag.DefaultReviewVersionId ?? (Model.Versions.FirstOrDefault()?.Id ?? 0));
                    var starCounts = Model.Reviews != null
                        ? Enumerable.Range(1, 5).Select(s => new { Star = s, Count = Model.Reviews.Count(r => r.Rating == s) }).OrderByDescending(x => x.Star).Cast<dynamic>().ToList()
                        : new List<dynamic>();
                    var total = Model.TotalReviews > 0 ? Model.TotalReviews : 1;
                

#line default
#line hidden
#nullable disable
            WriteLiteral("                <div class=\"glass-card p-4 mb-4\" id=\"review-section\">\r\n                    <h2 class=\"section-title\">Đánh giá & Nhận xét ");
#nullable restore
#line 184 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                             Write(Model.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral(@" <span id=""reviewVersionTitle"" class=""text-primary small"" style=""font-size:0.9rem;""></span></h2>
                    
                    <div class=""row align-items-center mb-4 pb-4 border-bottom"">
                        <!-- Rating Left -->
                        <div class=""col-md-4 text-center border-end"">
                            <div style=""font-size:3.5rem; font-weight:800; color:#d70018; line-height:1;"" id=""avgRatingNum"">");
#nullable restore
#line 189 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                                                       Write(Model.AverageRating.ToString("F1"));

#line default
#line hidden
#nullable disable
            WriteLiteral("<small style=\"font-size:1.5rem; color:#666;\">/5</small></div>\r\n                            <div class=\"text-warning mb-1 fs-5\" id=\"avgStars\">\r\n");
#nullable restore
#line 191 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                 for(int i=1;i<=5;i++){

#line default
#line hidden
#nullable disable
            WriteLiteral(" <i");
            BeginWriteAttribute("class", " class=\"", 10725, "\"", 10804, 2);
            WriteAttributeValue("", 10733, "bi", 10733, 2, true);
#nullable restore
#line 191 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue(" ", 10735, i <= Math.Round(Model.AverageRating) ? "bi-star-fill" : "bi-star", 10736, 68, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral("></i> ");
#nullable restore
#line 191 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                                                                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                            </div>\r\n                            <div class=\"text-muted fw-semibold\" id=\"totalReviewsText\">");
#nullable restore
#line 193 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                 Write(Model.TotalReviews);

#line default
#line hidden
#nullable disable
            WriteLiteral(" đánh giá</div>\r\n                        </div>\r\n                        \r\n                        <!-- Rating Bars -->\r\n                        <div class=\"col-md-5 py-3\" id=\"ratingBarsContainer\">\r\n");
#nullable restore
#line 198 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                             foreach(var item in starCounts) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                <div class=\"d-flex align-items-center gap-2 mb-1 review-bar-row\" data-star=\"");
#nullable restore
#line 199 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                                       Write(item.Star);

#line default
#line hidden
#nullable disable
            WriteLiteral("\" style=\"cursor:pointer;\"");
            BeginWriteAttribute("onclick", " onclick=\"", 11361, "\"", 11395, 3);
            WriteAttributeValue("", 11371, "filterByStar(", 11371, 13, true);
#nullable restore
#line 199 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 11384, item.Star, 11384, 10, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 11394, ")", 11394, 1, true);
            EndWriteAttribute();
            WriteLiteral(">\r\n                                    <span class=\"text-nowrap\" style=\"width:12px;\">");
#nullable restore
#line 200 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                             Write(item.Star);

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</span>
                                    <i class=""bi bi-star-fill text-warning""></i>
                                    <div class=""progress flex-grow-1"" style=""height:6px; background:#eee;"">
                                        <div class=""progress-bar""");
            BeginWriteAttribute("style", " style=\"", 11756, "\"", 11819, 4);
            WriteAttributeValue("", 11764, "width:", 11764, 6, true);
#nullable restore
#line 203 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 11770, item.Count * 100 / total, 11770, 27, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 11797, "%;", 11797, 2, true);
            WriteAttributeValue(" ", 11799, "background:#d70018;", 11800, 20, true);
            EndWriteAttribute();
            WriteLiteral("></div>\r\n                                    </div>\r\n                                    <span class=\"text-muted\" style=\"width:30px;\">");
#nullable restore
#line 205 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                            Write(item.Count);

#line default
#line hidden
#nullable disable
            WriteLiteral("</span>\r\n                                </div>\r\n");
#nullable restore
#line 207 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                            }

#line default
#line hidden
#nullable disable
            WriteLiteral("                        </div>\r\n                        \r\n                        <!-- Write/Edit Review Button -->\r\n");
#nullable restore
#line 211 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                         if (hasBought || existingReview != null) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                            <div class=\"col-md-3 text-center\">\r\n");
#nullable restore
#line 213 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                 if (existingReview != null) {
                                    if (existingReview.IsEdited) {

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                                        <p class=""small text-success mb-2""><i class=""bi bi-check-circle-fill me-1""></i>Đã đánh giá & sửa</p>
                                        <button class=""btn btn-outline-secondary w-100 rounded-3 fw-bold py-2"" disabled title=""Bạn chỉ được sửa đánh giá 1 lần"">
                                            ĐÃ HẾT LƯỢT SỬA
                                        </button>
");
#nullable restore
#line 219 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                    } else {

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                                        <p class=""small text-success mb-2""><i class=""bi bi-check-circle-fill me-1""></i>Đã đánh giá</p>
                                        <button class=""btn btn-outline-warning w-100 rounded-3 fw-bold py-2"" onclick=""toggleReviewForm()"">
                                            ✏️ SỬA ĐÁNH GIÁ (1 lần)
                                        </button>
");
#nullable restore
#line 224 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                    }
                                } else {

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                                    <p class=""small text-muted mb-2"">Bạn đã dùng sản phẩm này?</p>
                                    <button class=""btn btn-outline-danger w-100 rounded-3 fw-bold py-2"" onclick=""toggleReviewForm()"">
                                        VIẾT ĐÁNH GIÁ
                                    </button>
");
#nullable restore
#line 230 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                            </div>\r\n");
#nullable restore
#line 232 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                        } else {

#line default
#line hidden
#nullable disable
            WriteLiteral("                            <div class=\"col-md-3 text-center text-muted small\">\r\n");
#nullable restore
#line 234 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                 if (!User.Identity!.IsAuthenticated) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                    <a href=\"/Account/Login\" class=\"btn btn-sm btn-outline-danger rounded-pill px-3\">Đăng nhập để đánh giá</a>\r\n");
#nullable restore
#line 236 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                } else {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                    <span>Chỉ khách hàng đã mua sản phẩm mới được đánh giá</span>\r\n");
#nullable restore
#line 238 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                            </div>\r\n");
#nullable restore
#line 240 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                        }

#line default
#line hidden
#nullable disable
            WriteLiteral("                    </div>\r\n\r\n                    <!-- Inline Review Form (ẩn/hiện khi bấm nút) -->\r\n");
#nullable restore
#line 244 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                     if (canReview) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                        <div id=\"inline-review-form\" class=\"mb-4\" style=\"display:none;\">\r\n                            <div class=\"border rounded-4 overflow-hidden shadow-sm\" style=\"background:#fff;\">\r\n");
#nullable restore
#line 247 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                 if (existingReview != null) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                    <form asp-controller=\"Review\" asp-action=\"Edit\" method=\"post\" enctype=\"multipart/form-data\" id=\"reviewForm\">\r\n                                        ");
#nullable restore
#line 249 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                   Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                        <input type=\"hidden\" name=\"reviewId\"");
            BeginWriteAttribute("value", " value=\"", 15038, "\"", 15064, 1);
#nullable restore
#line 250 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 15046, existingReview.Id, 15046, 18, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" />\r\n                                        <input type=\"hidden\" name=\"ProductVersionId\"");
            BeginWriteAttribute("value", " value=\"", 15154, "\"", 15194, 1);
#nullable restore
#line 251 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 15162, existingReview.ProductVersionId, 15162, 32, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" id=\"reviewVersionId\" />\r\n                                        ");
#nullable restore
#line 252 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                   Write(await Html.PartialAsync("_ReviewModalBody", new ViewDataDictionary(ViewData) { { "ExistingReview", existingReview }, { "IsEdit", true } }));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                    </form>\r\n");
#nullable restore
#line 254 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                } else {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                    <form asp-controller=\"Review\" asp-action=\"Add\" method=\"post\" enctype=\"multipart/form-data\" id=\"reviewForm\">\r\n                                        ");
#nullable restore
#line 256 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                   Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                        <input type=\"hidden\" name=\"ProductVersionId\"");
            BeginWriteAttribute("value", " value=\"", 15784, "\"", 15809, 1);
#nullable restore
#line 257 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 15792, defaultVersionId, 15792, 17, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" id=\"reviewVersionId\" />\r\n                                        ");
#nullable restore
#line 258 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                   Write(await Html.PartialAsync("_ReviewModalBody", new ViewDataDictionary(ViewData) { { "ExistingReview", null }, { "IsEdit", false } }));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                    </form>\r\n");
#nullable restore
#line 260 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                            </div>\r\n                        </div>\r\n");
#nullable restore
#line 263 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                    }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                    <!-- Review Filters -->
                    <div class=""d-flex flex-wrap align-items-center gap-2 mb-4"">
                        <span class=""fw-bold small me-1"">Lọc:</span>
                        <button class=""btn btn-sm btn-danger border rounded-pill px-3 review-filter-btn active"" data-star=""0"" onclick=""filterByStar(0)"">Tất cả</button>
");
#nullable restore
#line 269 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                         for(int s=5; s>=1; s--) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                            <button class=\"btn btn-sm btn-light border rounded-pill px-3 review-filter-btn\" data-star=\"");
#nullable restore
#line 270 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                                                  Write(s);

#line default
#line hidden
#nullable disable
            WriteLiteral("\"");
            BeginWriteAttribute("onclick", " onclick=\"", 16721, "\"", 16747, 3);
            WriteAttributeValue("", 16731, "filterByStar(", 16731, 13, true);
#nullable restore
#line 270 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 16744, s, 16744, 2, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 16746, ")", 16746, 1, true);
            EndWriteAttribute();
            WriteLiteral(">");
#nullable restore
#line 270 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                                                                                 Write(s);

#line default
#line hidden
#nullable disable
            WriteLiteral(" ⭐</button>\r\n");
#nullable restore
#line 271 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                        }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                        <button class=""btn btn-sm btn-light border rounded-pill px-3 review-filter-btn"" data-star=""-1"" onclick=""filterByStar(-1)"">📷 Có ảnh</button>
                        <div class=""ms-auto"">
                            <select class=""form-select form-select-sm border rounded-pill"" id=""reviewSort"" onchange=""sortReviews(this.value)"" style=""width:160px;"">
                                <option value=""newest"">Mới nhất</option>
                                <option value=""rating-high"">Điểm cao nhất</option>
                                <option value=""rating-low"">Điểm thấp nhất</option>
                            </select>
                        </div>
                    </div>

                    <!-- Review List -->
                    <div id=""review-list-container"">
");
#nullable restore
#line 284 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                         if (Model.Reviews != null && Model.Reviews.Any())
                        {
                            foreach (var review in Model.Reviews)
                            {
                                List<string> reviewTags = new List<string>();
                                if (!string.IsNullOrEmpty(review.Tags)) {
                                    try { reviewTags = System.Text.Json.JsonSerializer.Deserialize<List<string>>(review.Tags) ?? new List<string>(); } catch {}
                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                                <div class=\"review-item d-flex gap-3 mb-4 pb-4 border-bottom\" \r\n                                     data-rating=\"");
#nullable restore
#line 293 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                             Write(review.Rating);

#line default
#line hidden
#nullable disable
            WriteLiteral("\" \r\n                                     data-version-id=\"");
#nullable restore
#line 294 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                 Write(review.ProductVersionId);

#line default
#line hidden
#nullable disable
            WriteLiteral("\"\r\n                                     data-has-img=\"");
#nullable restore
#line 295 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                               Write(!string.IsNullOrEmpty(review.ImageUrl) ? "1" : "0");

#line default
#line hidden
#nullable disable
            WriteLiteral("\" \r\n                                     data-date=\"");
#nullable restore
#line 296 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                           Write(review.CreatedAt.ToString("yyyyMMddHHmm"));

#line default
#line hidden
#nullable disable
            WriteLiteral(@""">
                                    <div class=""flex-shrink-0"">
                                        <div class=""rounded-circle d-flex align-items-center justify-content-center fw-bold text-white"" 
                                             style=""width:45px; height:45px; font-size:18px; background:linear-gradient(135deg,#d70018,#ff6b35);"">
                                            ");
#nullable restore
#line 300 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                        Write(string.IsNullOrEmpty(review.UserName) ? "?" : review.UserName[0].ToString().ToUpper());

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                                        </div>
                                    </div>
                                    <div class=""flex-grow-1"">
                                        <div class=""d-flex align-items-center gap-2 mb-1"">
                                            <span class=""fw-bold"">");
#nullable restore
#line 305 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                             Write(review.UserName);

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</span>
                                            <span class=""badge bg-success-subtle text-success border border-success-subtle small"" style=""font-size:10px;"">
                                                <i class=""bi bi-patch-check-fill me-1""></i>Đã mua tại HDKmall
                                            </span>
                                        </div>
                                        <div class=""text-warning small mb-2"">
");
#nullable restore
#line 311 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                             for(int s=1;s<=5;s++){

#line default
#line hidden
#nullable disable
            WriteLiteral(" <i");
            BeginWriteAttribute("class", " class=\"", 19946, "\"", 20005, 2);
            WriteAttributeValue("", 19954, "bi", 19954, 2, true);
#nullable restore
#line 311 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue(" ", 19956, s<=review.Rating ? "bi-star-fill" : "bi-star", 19957, 48, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral("></i> ");
#nullable restore
#line 311 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                                                                        }

#line default
#line hidden
#nullable disable
            WriteLiteral("                                            <span class=\"text-muted ms-2\" style=\"font-size:11px;\">");
#nullable restore
#line 312 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                             Write(review.CreatedAt.ToString("dd/MM/yyyy HH:mm"));

#line default
#line hidden
#nullable disable
            WriteLiteral("</span>\r\n                                        </div>\r\n                                        <!-- Tags -->\r\n");
#nullable restore
#line 315 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                         if (reviewTags.Any()) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                            <div class=\"d-flex flex-wrap gap-1 mb-2\">\r\n");
#nullable restore
#line 317 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                 foreach(var tag in reviewTags) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                                    <span class=\"badge rounded-pill border\" style=\"background:#f0f7ff; color:#1a6fcf; font-weight:500; font-size:11px; padding:4px 10px;\">");
#nullable restore
#line 318 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                                                                                                                     Write(tag);

#line default
#line hidden
#nullable disable
            WriteLiteral("</span>\r\n");
#nullable restore
#line 319 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                                            </div>\r\n");
#nullable restore
#line 321 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                        }

#line default
#line hidden
#nullable disable
            WriteLiteral("                                        <p class=\"text-dark small mb-2 lh-base\">");
#nullable restore
#line 322 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                           Write(review.Comment);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n                                        <!-- Review Image -->\r\n");
#nullable restore
#line 324 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                         if (!string.IsNullOrEmpty(review.ImageUrl)) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                            <div class=\"mb-2\">\r\n                                                <img");
            BeginWriteAttribute("src", " src=\"", 21220, "\"", 21242, 1);
#nullable restore
#line 326 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 21226, review.ImageUrl, 21226, 16, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" class=\"rounded-3 border review-img-thumb\" \r\n                                                     style=\"height:80px; width:80px; object-fit:cover; cursor:pointer;\"");
            BeginWriteAttribute("onclick", "\r\n                                                     onclick=\"", 21407, "\"", 21508, 3);
            WriteAttributeValue("", 21471, "openImageLightbox(\'", 21471, 19, true);
#nullable restore
#line 328 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 21490, review.ImageUrl, 21490, 16, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 21506, "\')", 21506, 2, true);
            EndWriteAttribute();
            WriteLiteral("\r\n                                                     alt=\"Ảnh đánh giá\" />\r\n                                            </div>\r\n");
#nullable restore
#line 331 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                        }

#line default
#line hidden
#nullable disable
            WriteLiteral("                                    </div>\r\n                                </div>\r\n");
#nullable restore
#line 334 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                            }
                        }
                        else {

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                            <div class=""text-center py-5"" id=""no-review-msg"">
                                <i class=""bi bi-chat-left-text text-muted"" style=""font-size:3rem;""></i>
                                <p class=""text-muted mt-3"">Sản phẩm này chưa có đánh giá nào.</p>
");
#nullable restore
#line 340 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                 if (canReview) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                    <button class=\"btn btn-danger btn-sm rounded-pill px-4\" onclick=\"toggleReviewForm()\">Viết đánh giá đầu tiên</button>\r\n");
#nullable restore
#line 342 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                            </div>\r\n");
#nullable restore
#line 344 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                        }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                    </div>
                </div>


                <!-- Image Lightbox -->
                <div class=""modal fade"" id=""imgLightboxModal"" tabindex=""-1"">
                    <div class=""modal-dialog modal-dialog-centered modal-lg"">
                        <div class=""modal-content bg-transparent border-0"">
                            <div class=""modal-body p-0 text-center position-relative"">
                                <button type=""button"" class=""btn-close btn-close-white position-absolute top-0 end-0 m-2"" data-bs-dismiss=""modal"" style=""z-index:10;""></button>
                                <img id=""lightboxImg""");
            BeginWriteAttribute("src", " src=\"", 23091, "\"", 23097, 0);
            EndWriteAttribute();
            WriteLiteral(@" class=""img-fluid rounded-4"" style=""max-height:85vh;"" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Right: Quick Specs Summary -->
            <div class=""col-lg-4"">
                <div class=""glass-card p-4"">
                    <h2 class=""section-title"" style=""font-size:15px;"">Điểm nổi bật</h2>
                    <ul class=""list-unstyled small text-muted"">
                        <li class=""py-2 border-bottom""><i class=""bi bi-shield-check text-success me-2""></i>Bảo hành 12 tháng chính hãng</li>
                        <li class=""py-2 border-bottom""><i class=""bi bi-arrow-repeat text-primary me-2""></i>Đổi trả trong 30 ngày</li>
                        <li class=""py-2 border-bottom""><i class=""bi bi-truck text-danger me-2""></i>Miễn phí giao hàng toàn quốc</li>
                        <li class=""py-2""><i class=""bi bi-credit-card text-warning me-2""></i>Hỗ trợ trả góp 0%</li>
              ");
            WriteLiteral("      </ul>\r\n                </div>\r\n            </div>\r\n        </div>\r\n\r\n        <!-- Related Products Section (CellphoneS style) -->\r\n");
#nullable restore
#line 376 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
         if (ViewBag.RelatedProducts != null && ((List<ProductListVM>)ViewBag.RelatedProducts).Any())
        {

#line default
#line hidden
#nullable disable
            WriteLiteral("            <div class=\"mt-5 pt-4 border-top\">\r\n                <h3 class=\"fw-bold mb-4\">Sản phẩm tương tự</h3>\r\n                <div class=\"row row-cols-2 row-cols-md-4 row-cols-lg-5 g-3\">\r\n");
#nullable restore
#line 381 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                     foreach (var item in (List<ProductListVM>)ViewBag.RelatedProducts)
                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                        <div class=\"col\">\r\n                            <div class=\"pl-product-card h-100 shadow-sm border rounded-4 overflow-hidden\" style=\"background:#fff;\">\r\n                                <a");
            BeginWriteAttribute("href", " href=\"", 24886, "\"", 25000, 3);
            WriteAttributeValue("", 24893, "/product/", 24893, 9, true);
#nullable restore
#line 385 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 24902, item.Slug ?? item.Id.ToString(), 24902, 34, false);

#line default
#line hidden
#nullable disable
#nullable restore
#line 385 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 24936, item.VersionId.HasValue ? "?versionId=" + item.VersionId : "", 24936, 64, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" \r\n                                   class=\"img-box d-block text-center p-3\" style=\"height:180px; background:#fff;\">\r\n                                    <img");
            BeginWriteAttribute("src", " src=\"", 25160, "\"", 25212, 1);
#nullable restore
#line 387 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 25166, item.ImageUrl ?? "/img/Product_Default.jpg", 25166, 46, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" class=\"img-fluid\" \r\n                                         style=\"max-height:100%; object-fit:contain;\"");
            BeginWriteAttribute("alt", " alt=\"", 25319, "\"", 25335, 1);
#nullable restore
#line 388 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 25325, item.Name, 25325, 10, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" onerror=""this.src='/img/Product_Default.jpg'"">
                                </a>
                                <div class=""p-3 d-flex flex-column flex-grow-1"">
                                    <div class=""text-muted mb-1"" style=""font-size:11px;"">");
#nullable restore
#line 391 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                     Write(item.BrandName ?? "Chính hãng");

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n                                    <a");
            BeginWriteAttribute("href", " href=\"", 25673, "\"", 25787, 3);
            WriteAttributeValue("", 25680, "/product/", 25680, 9, true);
#nullable restore
#line 392 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 25689, item.Slug ?? item.Id.ToString(), 25689, 34, false);

#line default
#line hidden
#nullable disable
#nullable restore
#line 392 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue("", 25723, item.VersionId.HasValue ? "?versionId=" + item.VersionId : "", 25723, 64, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" 
                                       class=""text-decoration-none text-dark fw-bold lh-sm mb-2"" 
                                       style=""font-size:14px; display:-webkit-box; -webkit-line-clamp:2; -webkit-box-orient:vertical; overflow:hidden; min-height:36px;"">");
#nullable restore
#line 394 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                                                                                                    Write(item.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</a>\r\n                                    \r\n                                    <div class=\"mt-auto\">\r\n                                        <div class=\"text-danger fw-bold fs-6 mb-2\">\r\n");
#nullable restore
#line 398 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                             if (item.Price > 0) {
                                                

#line default
#line hidden
#nullable disable
#nullable restore
#line 399 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                           Write(item.Price.ToString("N0"));

#line default
#line hidden
#nullable disable
            WriteLiteral("₫");
#nullable restore
#line 399 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                                        
                                            } else {
                                                

#line default
#line hidden
#nullable disable
            WriteLiteral("Liên hệ");
#nullable restore
#line 401 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                    
                                            }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                                        </div>
                                        <div class=""d-flex align-items-center justify-content-between mt-1"">
                                            <div style=""color:#ffc107; font-size:11px; display:flex; align-items:center; gap:2px;"">
");
#nullable restore
#line 406 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                 for (int s = 1; s <= 5; s++) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                                    <span>");
#nullable restore
#line 407 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                      Write(s <= Math.Round(item.AverageRating) ? "★" : "☆");

#line default
#line hidden
#nullable disable
            WriteLiteral("</span>\r\n");
#nullable restore
#line 408 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                                                <span class=\"text-muted ms-1\">");
#nullable restore
#line 409 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                                                                         Write(item.AverageRating.ToString("F1"));

#line default
#line hidden
#nullable disable
            WriteLiteral("</span>\r\n                                            </div>\r\n                                            <button type=\"button\" class=\"pl-wishlist-btn\"");
            BeginWriteAttribute("onclick", " onclick=\"", 27388, "\"", 27459, 6);
            WriteAttributeValue("", 27398, "toggleWishlist(event,", 27398, 21, true);
#nullable restore
#line 411 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue(" ", 27419, item.Id, 27420, 8, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 27428, ",", 27428, 1, true);
#nullable restore
#line 411 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
WriteAttributeValue(" ", 27429, item.VersionId ?? 0, 27430, 22, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 27452, ",", 27452, 1, true);
            WriteAttributeValue(" ", 27453, "this)", 27454, 6, true);
            EndWriteAttribute();
            WriteLiteral(@" title=""Yêu thích"">
                                                <svg xmlns=""http://www.w3.org/2000/svg"" width=""16"" height=""16"" fill=""currentColor"" viewBox=""0 0 16 16"">
                                                    <path d=""M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748z""/>
                                                </svg>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
");
#nullable restore
#line 421 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                    }

#line default
#line hidden
#nullable disable
            WriteLiteral("                </div>\r\n            </div>\r\n");
#nullable restore
#line 424 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
        }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"    </div>
</div>

<!-- Image Zoom Modal (Lightbox) -->
<div class=""modal fade"" id=""imageZoomModal"" tabindex=""-1"" aria-hidden=""true"">
    <div class=""modal-dialog modal-dialog-centered modal-xl"">
        <div class=""modal-content border-0 bg-transparent"">
            <div class=""modal-body p-0 position-relative text-center"">
                <button type=""button"" class=""btn-close btn-close-white position-absolute top-0 end-0 m-3"" data-bs-dismiss=""modal"" aria-label=""Close"" style=""z-index: 1060;""></button>
                <img id=""zoomedImg""");
            BeginWriteAttribute("src", " src=\"", 28858, "\"", 28864, 0);
            EndWriteAttribute();
            WriteLiteral(" class=\"img-fluid rounded shadow-lg\" style=\"max-height: 90vh; object-fit: contain;\" />\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script>\r\n    const productData = ");
#nullable restore
#line 441 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                   Write(Html.Raw(System.Text.Json.JsonSerializer.Serialize(Model, new System.Text.Json.JsonSerializerOptions { ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles })));

#line default
#line hidden
#nullable disable
            WriteLiteral(@";
    let currentVersion = null;
    let currentVariant = null;

    function goToVersion(id) {
        // Redirection to update version-specific content (Reviews, HasBought, etc.)
        const currentUrl = new URL(window.location.href);
        currentUrl.searchParams.set('versionId', id);
        window.location.href = currentUrl.toString();
    }

    function selectVersion(id) {
        currentVersion = productData.Versions.find(v => v.Id === id);
        if (!currentVersion) return;
        
        // Sync with review form (if it exists)
        const rvInp = document.getElementById('reviewVersionId');
        if (rvInp) rvInp.value = id;
        
        // Update Active UI
        document.querySelectorAll('[data-version-id]').forEach(el => {
            el.classList.toggle('active', parseInt(el.dataset.versionId) === id);
        });

        // Update Colors
        const colorWrap = document.getElementById('colorSelector');
        colorWrap.innerHTML = '';
        curre");
            WriteLiteral(@"ntVersion.Variants.forEach(vr => {
            const item = document.createElement('div');
            item.className = 'option-item';
            item.innerHTML = `<span class=""option-name"">${vr.Color}</span>`;
            item.onclick = () => selectVariant(vr);
            item.dataset.variantId = vr.Id;
            colorWrap.appendChild(item);
        });

        // Update Description
        document.getElementById('versionDescription').innerHTML = 
            (currentVersion.Description || productData.Description || 'Đang cập nhật...').replace(/\n/g, '<br/>');

        // Update Specs
        const specWrap = document.getElementById('specContainer');
        specWrap.innerHTML = '<table class=""table table-sm border-0 small""><tbody></tbody></table>';
        const tbody = specWrap.querySelector('tbody');
        currentVersion.Specifications.forEach(s => {
            tbody.innerHTML += `<tr><td class=""text-muted border-0 py-2"">${s.SpecName}</td><td class=""fw-bold border-0 py-2 text-en");
            WriteLiteral(@"d"">${s.SpecValue}</td></tr>`;
        });

        // Select first variant by default
        if (currentVersion.Variants.length > 0) {
            selectVariant(currentVersion.Variants[0]);
        } else {
            updatePrice(currentVersion.BasePrice);
        }

        updateGallery();
        updateReviewStats();
        applyReviewFilters();

        // Update Review Form fields
        const rvIdInp = document.getElementById('reviewVersionId');
        if (rvIdInp) rvIdInp.value = currentVersion.Id;
        
        const rvName = document.getElementById('reviewProductName');
        if (rvName) rvName.innerText = productData.Name;
        
        const rvVer = document.getElementById('reviewProductVersion');
        if (rvVer) rvVer.innerText = `Phiên bản: ${currentVersion.Name}`;
        
        const rvImg = document.getElementById('reviewProductImg');
        if (rvImg) {
            const imgSrc = currentVersion.ImageUrl || productData.ImageUrl || '/img/default.png'");
            WriteLiteral(@";
            rvImg.innerHTML = `<img src=""${imgSrc}"" class=""img-fluid"" style=""max-height:100%; object-fit:contain;"">`;
        }
    }

    function updateReviewStats() {
        const vId = currentVersion.Id;
        const reviews = productData.Reviews.filter(r => r.ProductVersionId === vId);
        // Update Title
        document.getElementById('reviewVersionTitle').innerText = `- Phiên bản ${currentVersion.Name}`;

        const total = reviews.length;
        const avg = total > 0 ? reviews.reduce((sum, r) => sum + r.Rating, 0) / total : 0;

        // Update Big Number
        document.getElementById('avgRatingNum').innerHTML = `${avg.toFixed(1)}<small style=""font-size:1.5rem; color:#666;"">/5</small>`;
        
        // Update Stars
        let starHtml = '';
        const roundAvg = Math.round(avg);
        for(let i=1; i<=5; i++) {
            starHtml += `<i class=""bi ${i <= roundAvg ? 'bi-star-fill' : 'bi-star'}""></i> `;
        }
        document.getElementById('avgStars'");
            WriteLiteral(@").innerHTML = starHtml;
        document.getElementById('totalReviewsText').innerText = `${total} đánh giá`;

        // Update Bars
        const barContainer = document.getElementById('ratingBarsContainer');
        let barsHtml = '';
        const divisor = total > 0 ? total : 1;
        for(let s=5; s>=1; s--) {
            const count = reviews.filter(r => r.Rating === s).length;
            const percent = (count * 100 / divisor);
            barsHtml += `
                <div class=""d-flex align-items-center gap-2 mb-1 review-bar-row"" data-star=""${s}"" style=""cursor:pointer;"" onclick=""filterByStar(${s})"">
                    <span class=""text-nowrap"" style=""width:12px;"">${s}</span>
                    <i class=""bi bi-star-fill text-warning""></i>
                    <div class=""progress flex-grow-1"" style=""height:6px; background:#eee;"">
                        <div class=""progress-bar"" style=""width:${percent}%; background:#d70018;""></div>
                    </div>
                    <s");
            WriteLiteral(@"pan class=""text-muted"" style=""width:30px;"">${count}</span>
                </div>`;
        }
        barContainer.innerHTML = barsHtml;
    }

    function selectVariant(vr) {
        currentVariant = vr;
        document.querySelectorAll('#colorSelector .option-item').forEach(el => {
            el.classList.toggle('active', parseInt(el.dataset.variantId) === vr.Id);
        });
        
        const displayPrice = vr.Price > 0 ? vr.Price : currentVersion.BasePrice;
        updatePrice(displayPrice, currentVersion.OriginalPrice);

        if (vr.ImageUrl) {
            document.getElementById('mainDisplayImg').src = vr.ImageUrl;
        }
    }

    function updatePrice(price, originalPrice) {
        document.getElementById('activePrice').innerText = price.toLocaleString('vi-VN') + '₫';
        
        const origEl = document.getElementById('activeOriginalPrice');
        const badgeEl = document.getElementById('activeDiscountBadge');
        
        if (originalPrice && origin");
            WriteLiteral(@"alPrice > price) {
            origEl.innerText = originalPrice.toLocaleString('vi-VN') + '₫';
            origEl.style.display = 'block';
            
            const pct = Math.round((1 - price / originalPrice) * 100);
            badgeEl.innerText = '-' + pct + '%';
            badgeEl.style.display = 'inline-block';
        } else {
            origEl.style.display = 'none';
            badgeEl.style.display = 'none';
        }
    }

    function updateGallery() {
        const thumbWrap = document.getElementById('galleryThumbs');
        thumbWrap.innerHTML = '';
        
        const imgs = [];
        if (productData.Images && productData.Images.length > 0) {
            productData.Images.forEach(img => imgs.push(img.ImageUrl));
        }
        if (currentVersion.ImageUrl) imgs.push(currentVersion.ImageUrl);
        currentVersion.Variants.forEach(v => { if(v.ImageUrl) imgs.push(v.ImageUrl); });
        
        [...new Set(imgs)].forEach((src, i) => {
            const ");
            WriteLiteral(@"img = document.createElement('img');
            img.src = src;
            img.className = 'thumb-item' + (i === 0 ? ' active' : '');
            img.onclick = () => {
                document.getElementById('mainDisplayImg').src = src;
                document.querySelectorAll('.thumb-item').forEach(t => t.classList.remove('active'));
                img.classList.add('active');
            };
            thumbWrap.appendChild(img);
        });
    }

    function handleAddToCart() {
        if (!currentVariant) {
            Swal.fire({ title: 'Thông báo', text: 'Vui lòng chọn màu sắc', icon: 'info', confirmButtonColor: '#d70018' });
            return;
        }
        
        fetch('/Cart/Add', {
            method: 'POST',
            headers: { 
                'Content-Type': 'application/x-www-form-urlencoded',
                'X-Requested-With': 'XMLHttpRequest'
            },
            body: `productId=${productData.Id}&variantId=${currentVariant.Id}&quantity=1`
       ");
            WriteLiteral(@" }).then(r => r.json()).then(data => {
            if(data.success) {
                showSuccessToast('Thêm vào giỏ hàng thành công');
                updateCartBadge(data.cartCount);
            } else {
                Swal.fire('Thông báo', data.message || 'Lỗi thêm vào giỏ', 'error');
            }
        });
    }

    function handleBuyNow() {
        if (!currentVariant) {
            Swal.fire({ title: 'Thông báo', text: 'Vui lòng chọn màu sắc', icon: 'info', confirmButtonColor: '#d70018' });
            return;
        }
        handleAddToCart();
        window.location.href = '/Cart';
    }

    // Init
    window.onload = () => {
        const requestedVersionId = ");
#nullable restore
#line 649 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Product\Detail.cshtml"
                               Write(ViewBag.RequestedVersionId ?? "null");

#line default
#line hidden
#nullable disable
            WriteLiteral(@";
        if (productData.Versions.length > 0) {
            if (requestedVersionId && productData.Versions.some(v => v.Id === requestedVersionId)) {
                selectVersion(requestedVersionId);
            } else {
                selectVersion(productData.Versions[0].Id);
            }
        }
        

        // Wishlist logic
        const wishlistKey = 'hdkmall_wishlist';
        function getWishlist() { try { return JSON.parse(localStorage.getItem(wishlistKey) || '[]'); } catch { return []; } }
        function saveWishlist(list) { localStorage.setItem(wishlistKey, JSON.stringify(list)); }
        
        window.toggleWishlist = function(e, productId, versionId, btn) {
            e.preventDefault(); e.stopPropagation();
            const list = getWishlist();
            const key = productId + '_' + (versionId || 0);
            const idx = list.indexOf(key);
            if (idx === -1) {
                list.push(key);
                btn.classList.add('active');
    ");
            WriteLiteral(@"            showSuccessToast('❤️ Đã thêm vào yêu thích!');
            } else {
                list.splice(idx, 1);
                btn.classList.remove('active');
                showSuccessToast('💔 Đã xóa khỏi yêu thích');
            }
            saveWishlist(list);
        };

        // Mark wishlisted items
        const list = getWishlist();
        document.querySelectorAll('.pl-wishlist-btn').forEach(btn => {
            const onclick = btn.getAttribute('onclick') || '';
            const match = onclick.match(/toggleWishlist\(event,\s*(\d+),\s*(\d+)/);
            if (match) {
                const key = match[1] + '_' + match[2];
                if (list.includes(key)) btn.classList.add('active');
            }
        });
    };

    function openZoomModal() {
        const src = document.getElementById('mainDisplayImg').src;
        document.getElementById('zoomedImg').src = src;
        const modal = new bootstrap.Modal(document.getElementById('imageZoomModal'));
    ");
            WriteLiteral(@"    modal.show();
    }

    // ====== Review Filter & Sort (Client-side) ======
    let currentStarFilter = 0;
    let currentSort = 'newest';

    function filterByStar(star) {
        currentStarFilter = star;
        // Update active button state
        document.querySelectorAll('.review-filter-btn').forEach(btn => {
            btn.classList.remove('active', 'btn-danger');
            btn.classList.add('btn-light');
        });
        const activeBtn = document.querySelector(`.review-filter-btn[data-star=""${star}""]`);
        if (activeBtn) {
            activeBtn.classList.remove('btn-light');
            activeBtn.classList.add('btn-danger', 'active');
        }
        applyReviewFilters();
    }

    function sortReviews(sortVal) {
        currentSort = sortVal;
        applyReviewFilters();
    }

    function applyReviewFilters() {
        const items = Array.from(document.querySelectorAll('.review-item'));
        let visible = items;

        // Filter by Version ");
            WriteLiteral(@"(STRICT)
        visible = items.filter(el => parseInt(el.dataset.versionId) === currentVersion.Id);

        // Filter by Stars/Image
        if (currentStarFilter === -1) {
            visible = visible.filter(el => el.dataset.hasImg === '1');
        } else if (currentStarFilter > 0) {
            visible = visible.filter(el => parseInt(el.dataset.rating) === currentStarFilter);
        }

        // Sort
        visible.sort((a, b) => {
            if (currentSort === 'rating-high') return parseInt(b.dataset.rating) - parseInt(a.dataset.rating);
            if (currentSort === 'rating-low') return parseInt(a.dataset.rating) - parseInt(b.dataset.rating);
            return b.dataset.date.localeCompare(a.dataset.date); // newest
        });

        // Re-render: hide all, show sorted visible
        const container = document.getElementById('review-list-container');
        items.forEach(el => el.style.display = 'none');
        const noMsg = document.getElementById('no-review-msg');
");
            WriteLiteral(@"
        if (visible.length === 0) {
            if (!noMsg) {
                const div = document.createElement('div');
                div.id = 'filter-empty-msg';
                div.className = 'text-center py-4 text-muted';
                div.innerHTML = '<i class=""bi bi-search"" style=""font-size:2rem;""></i><p class=""mt-2"">Không có đánh giá nào phù hợp</p>';
                container.appendChild(div);
            }
        } else {
            const old = document.getElementById('filter-empty-msg');
            if (old) old.remove();
            visible.forEach(el => {
                el.style.display = '';
                container.appendChild(el); // re-order in DOM
            });
        }
    }

    // Image lightbox
    function openImageLightbox(src) {
        const img = document.getElementById('lightboxImg');
        if (img) img.src = src;
        const modal = new bootstrap.Modal(document.getElementById('imgLightboxModal'));
        modal.show();
    }

    function ");
            WriteLiteral(@"updateCartBadge(count) {
        const badge = document.getElementById('cart-badge');
        if (badge) {
            badge.textContent = count;
            badge.classList.toggle('d-none', count <= 0);
        }
    }

    function toggleReviewForm() {
        const form = document.getElementById('inline-review-form');
        if (form.style.display === 'none') {
            form.style.display = 'block';
            form.scrollIntoView({ behavior: 'smooth', block: 'center' });
        } else {
            form.style.display = 'none';
        }
    }

    // Auto-open review form if requested via URL
    window.addEventListener('load', function() {
        const url = new URL(window.location.href);
        const urlParams = url.searchParams;
        if (urlParams.get('autoReview') === 'true') {
            setTimeout(() => {
                toggleReviewForm();
                // Clear the parameter so it doesn't open again on refresh
                urlParams.delete('autoReview');
");
            WriteLiteral(@"                window.history.replaceState({}, document.title, url.toString());
            }, 600); 
        }
    });
</script>

<style>
    .cursor-pointer { cursor: pointer; }
    .text-truncate-2 { display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
    
    /* Related Products Styles */
    .pl-product-card { background:#fff; border-radius:10px; border:1.5px solid #f0f0f0; overflow:hidden; transition:all .2s; display:flex; flex-direction:column; }
    .pl-product-card:hover { border-color:#d70018; box-shadow:0 6px 18px rgba(215,0,24,.1); transform:translateY(-3px); }
    .pl-product-card .img-box { background:#fafafa; aspect-ratio:1/1; display:flex; align-items:center; justify-content:center; padding:12px; }
    .pl-product-card img { max-height:100%; object-fit:contain; transition:transform .2s; }
    .pl-product-card:hover img { transform:scale(1.05); }
    .pl-wishlist-btn { background:none; border:none; padding:0; cursor:pointer; color:#aaa");
            WriteLiteral(@"; font-size:18px; transition:color .2s; display:flex; align-items:center; gap:4px; }
    .pl-wishlist-btn:hover, .pl-wishlist-btn.active { color:#d70018; }

    /* Inline Review Form Styling */
    #inline-review-form {
        animation: slideDown 0.3s ease-out;
        border: 1px solid #f0f0f0;
        border-radius: 16px;
        overflow: hidden;
    }
    ");
            WriteLiteral("@keyframes slideDown {\r\n        from { opacity: 0; transform: translateY(-20px); }\r\n        to { opacity: 1; transform: translateY(0); }\r\n    }\r\n</style>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
