// <auto-generated />
using System;
using HDKmall.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HDKmall.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415165118_AddUserAddressManagement")]
    partial class AddUserAddressManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HDKmall.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/banner-iphone15.jpg",
                            IsActive = true,
                            LinkUrl = "/Product/Detail/iphone-15-pro-max",
                            Title = "iPhone 15 Pro Max - Công Nghệ Mới Nhất"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/banner-s24.jpg",
                            IsActive = true,
                            LinkUrl = "/Product/Detail/samsung-galaxy-s24-ultra",
                            Title = "Samsung Galaxy S24 - Siêu Phẩm 2024"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/banner-mbpro.jpg",
                            IsActive = true,
                            LinkUrl = "/Product/Detail/macbook-pro-16",
                            Title = "MacBook Pro - Hiệu Năng Vượt Trội"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/banner-sale.jpg",
                            IsActive = true,
                            LinkUrl = "/Product/Index",
                            Title = "Khuyến Mãi Lớn - Giảm Giá Đến 40%"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/banner-accessories.jpg",
                            IsActive = true,
                            LinkUrl = "/Product/Index?category=5",
                            Title = "Phụ Kiện Chính Hãng - Giá Tốt Nhất"
                        });
                });

            modelBuilder.Entity("HDKmall.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sản phẩm từ Apple Inc.",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sản phẩm từ Samsung",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sản phẩm từ Xiaomi",
                            Name = "Xiaomi"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sản phẩm từ Oppo",
                            Name = "Oppo"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sản phẩm từ Vivo",
                            Name = "Vivo"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sản phẩm từ Sony",
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sản phẩm từ Anker",
                            Name = "Anker"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Sản phẩm từ JBL",
                            Name = "JBL"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sản phẩm từ Soundcore",
                            Name = "Soundcore"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Sản phẩm từ Realme",
                            Name = "Realme"
                        });
                });

            modelBuilder.Entity("HDKmall.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("HDKmall.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các loại điện thoại di động",
                            Name = "Điện thoại"
                        },
                        new
                        {
                            Id = 2,
                            Description = "iPad, Samsung Tab, v.v.",
                            Name = "Máy tính bảng"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Máy tính xách tay",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tai nghe Bluetooth, có dây",
                            Name = "Tai nghe"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cáp, bộ sạc, ốp lưng",
                            Name = "Phụ kiện"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Smart watch",
                            Name = "Đồng hồ thông minh"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Máy ảnh, webcam",
                            Name = "Camera"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Loa Bluetooth, loa để bàn",
                            Name = "Loa"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Power bank, sạc dự phòng",
                            Name = "Pin sạc"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Bộ chơi game, đồ chơi công nghệ",
                            Name = "Game & Toy"
                        });
                });

            modelBuilder.Entity("HDKmall.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "WELCOME2024",
                            DiscountAmount = 500000m,
                            ExpiryDate = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 100,
                            UsedCount = 25
                        },
                        new
                        {
                            Id = 2,
                            Code = "SAVE10",
                            DiscountAmount = 1000000m,
                            ExpiryDate = new DateTime(2025, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 50,
                            UsedCount = 40
                        },
                        new
                        {
                            Id = 3,
                            Code = "BIGDEAL",
                            DiscountAmount = 2000000m,
                            ExpiryDate = new DateTime(2025, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 30,
                            UsedCount = 10
                        },
                        new
                        {
                            Id = 4,
                            Code = "NEWYEAR",
                            DiscountAmount = 3000000m,
                            ExpiryDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 20,
                            UsedCount = 8
                        },
                        new
                        {
                            Id = 5,
                            Code = "STUDENT",
                            DiscountAmount = 500000m,
                            ExpiryDate = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 200,
                            UsedCount = 120
                        },
                        new
                        {
                            Id = 6,
                            Code = "VIPUSER",
                            DiscountAmount = 5000000m,
                            ExpiryDate = new DateTime(2025, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 10,
                            UsedCount = 3
                        },
                        new
                        {
                            Id = 7,
                            Code = "FLASH50",
                            DiscountAmount = 10000000m,
                            ExpiryDate = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 5,
                            UsedCount = 2
                        });
                });

            modelBuilder.Entity("HDKmall.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HDKmall.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("HDKmall.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Flagship Apple 2024",
                            ImageUrl = "/images/iphone15promax.jpg",
                            Name = "iPhone 15 Pro Max",
                            Price = 29999000m
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Pro model 2024",
                            ImageUrl = "/images/iphone15pro.jpg",
                            Name = "iPhone 15 Pro",
                            Price = 24999000m
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Standard model 2024",
                            ImageUrl = "/images/iphone15.jpg",
                            Name = "iPhone 15",
                            Price = 19999000m
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Pro model 2023",
                            ImageUrl = "/images/iphone14pro.jpg",
                            Name = "iPhone 14 Pro",
                            Price = 21999000m
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Budget friendly",
                            ImageUrl = "/images/iphonese.jpg",
                            Name = "iPhone SE",
                            Price = 12999000m
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Ultra flagship 2024",
                            ImageUrl = "/images/s24ultra.jpg",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 28999000m
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Standard flagship",
                            ImageUrl = "/images/s24.jpg",
                            Name = "Samsung Galaxy S24",
                            Price = 22999000m
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Mid-range phone",
                            ImageUrl = "/images/a55.jpg",
                            Name = "Samsung Galaxy A55",
                            Price = 10999000m
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Foldable phone",
                            ImageUrl = "/images/zfold5.jpg",
                            Name = "Samsung Galaxy Z Fold5",
                            Price = 39999000m
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            CategoryId = 2,
                            Description = "Premium tablet",
                            ImageUrl = "/images/tabs9.jpg",
                            Name = "Samsung Galaxy Tab S9",
                            Price = 18999000m
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "Premium Xiaomi",
                            ImageUrl = "/images/xiaomi14ultra.jpg",
                            Name = "Xiaomi 14 Ultra",
                            Price = 21999000m
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "Standard flagship",
                            ImageUrl = "/images/xiaomi14.jpg",
                            Name = "Xiaomi 14",
                            Price = 17999000m
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "Budget choice",
                            ImageUrl = "/images/redminote13.jpg",
                            Name = "Xiaomi Redmi Note 13",
                            Price = 8999000m
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            CategoryId = 2,
                            Description = "Budget tablet",
                            ImageUrl = "/images/xiaomipad6.jpg",
                            Name = "Xiaomi Pad 6",
                            Price = 15999000m
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "Last year flagship",
                            ImageUrl = "/images/xiaomi13tpro.jpg",
                            Name = "Xiaomi 13T Pro",
                            Price = 19999000m
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 4,
                            CategoryId = 1,
                            Description = "Premium flagship",
                            ImageUrl = "/images/findx7ultra.jpg",
                            Name = "Oppo Find X7 Ultra",
                            Price = 27999000m
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 4,
                            CategoryId = 1,
                            Description = "Standard flagship",
                            ImageUrl = "/images/findx7.jpg",
                            Name = "Oppo Find X7",
                            Price = 23999000m
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 4,
                            CategoryId = 1,
                            Description = "Mid-range phone",
                            ImageUrl = "/images/reno11.jpg",
                            Name = "Oppo Reno 11",
                            Price = 12999000m
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 4,
                            CategoryId = 1,
                            Description = "Budget phone",
                            ImageUrl = "/images/a79.jpg",
                            Name = "Oppo A79",
                            Price = 6999000m
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 4,
                            CategoryId = 2,
                            Description = "Budget tablet",
                            ImageUrl = "/images/opad2.jpg",
                            Name = "Oppo Pad 2",
                            Price = 12999000m
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 5,
                            CategoryId = 1,
                            Description = "Premium flagship",
                            ImageUrl = "/images/x100pro.jpg",
                            Name = "Vivo X100 Pro",
                            Price = 25999000m
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 5,
                            CategoryId = 1,
                            Description = "Standard flagship",
                            ImageUrl = "/images/x100.jpg",
                            Name = "Vivo X100",
                            Price = 21999000m
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 5,
                            CategoryId = 1,
                            Description = "Mid-range phone",
                            ImageUrl = "/images/v40.jpg",
                            Name = "Vivo V40",
                            Price = 13999000m
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 5,
                            CategoryId = 1,
                            Description = "Budget phone",
                            ImageUrl = "/images/y100.jpg",
                            Name = "Vivo Y100",
                            Price = 6999000m
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 5,
                            CategoryId = 2,
                            Description = "Budget tablet",
                            ImageUrl = "/images/vpad.jpg",
                            Name = "Vivo Pad",
                            Price = 13999000m
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 1,
                            CategoryId = 2,
                            Description = "Premium tablet",
                            ImageUrl = "/images/ipadpro129.jpg",
                            Name = "iPad Pro 12.9",
                            Price = 27999000m
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 1,
                            CategoryId = 2,
                            Description = "Mid-range tablet",
                            ImageUrl = "/images/ipadair.jpg",
                            Name = "iPad Air",
                            Price = 18999000m
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 1,
                            CategoryId = 3,
                            Description = "Premium laptop",
                            ImageUrl = "/images/mbpro16.jpg",
                            Name = "MacBook Pro 16\"",
                            Price = 69999000m
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 1,
                            CategoryId = 3,
                            Description = "Entry-level pro laptop",
                            ImageUrl = "/images/mbairrm3.jpg",
                            Name = "MacBook Air M3",
                            Price = 42999000m
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 1,
                            CategoryId = 3,
                            Description = "Previous M2 Air",
                            ImageUrl = "/images/mbatrm2.jpg",
                            Name = "MacBook Air M2",
                            Price = 37999000m
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 1,
                            CategoryId = 4,
                            Description = "Premium earbuds",
                            ImageUrl = "/images/airpodspro2.jpg",
                            Name = "AirPods Pro 2",
                            Price = 5999000m
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 1,
                            CategoryId = 4,
                            Description = "Premium headphones",
                            ImageUrl = "/images/airpodsmax.jpg",
                            Name = "AirPods Max",
                            Price = 18999000m
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 2,
                            CategoryId = 4,
                            Description = "Premium earbuds",
                            ImageUrl = "/images/galaxybuds2pro.jpg",
                            Name = "Samsung Galaxy Buds2 Pro",
                            Price = 4999000m
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 6,
                            CategoryId = 4,
                            Description = "Premium headphones",
                            ImageUrl = "/images/sonywh1000xm5.jpg",
                            Name = "Sony WH-1000XM5",
                            Price = 7999000m
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 8,
                            CategoryId = 4,
                            Description = "Good earbuds",
                            ImageUrl = "/images/jbllivepro2.jpg",
                            Name = "JBL Live Pro 2",
                            Price = 5999000m
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 1,
                            CategoryId = 6,
                            Description = "Premium smartwatch",
                            ImageUrl = "/images/watchultra2.jpg",
                            Name = "Apple Watch Ultra 2",
                            Price = 12999000m
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 1,
                            CategoryId = 6,
                            Description = "Standard smartwatch",
                            ImageUrl = "/images/watchs9.jpg",
                            Name = "Apple Watch Series 9",
                            Price = 8999000m
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 2,
                            CategoryId = 6,
                            Description = "Premium Android watch",
                            ImageUrl = "/images/watch6pro.jpg",
                            Name = "Samsung Galaxy Watch6 Pro",
                            Price = 8999000m
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 3,
                            CategoryId = 6,
                            Description = "Budget smartwatch",
                            ImageUrl = "/images/watchs3.jpg",
                            Name = "Xiaomi Watch S3",
                            Price = 4999000m
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 10,
                            CategoryId = 6,
                            Description = "Entry smartwatch",
                            ImageUrl = "/images/watch3.jpg",
                            Name = "Realme Watch 3",
                            Price = 3999000m
                        },
                        new
                        {
                            Id = 41,
                            BrandId = 6,
                            CategoryId = 7,
                            Description = "Professional camera",
                            ImageUrl = "/images/a7rv.jpg",
                            Name = "Sony A7R V",
                            Price = 54999000m
                        },
                        new
                        {
                            Id = 42,
                            BrandId = 6,
                            CategoryId = 7,
                            Description = "Mirrorless camera",
                            ImageUrl = "/images/a6700.jpg",
                            Name = "Sony A6700",
                            Price = 24999000m
                        },
                        new
                        {
                            Id = 43,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Excellent camera phone",
                            ImageUrl = "/images/s24cam.jpg",
                            Name = "Samsung Galaxy S24 Camera",
                            Price = 22999000m
                        },
                        new
                        {
                            Id = 44,
                            BrandId = 6,
                            CategoryId = 7,
                            Description = "Professional drone",
                            ImageUrl = "/images/djimini4pro.jpg",
                            Name = "DJI Mini 4 Pro",
                            Price = 18999000m
                        },
                        new
                        {
                            Id = 45,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Amazing camera phone",
                            ImageUrl = "/images/ip15cam.jpg",
                            Name = "iPhone 15 Pro Max Camera",
                            Price = 29999000m
                        },
                        new
                        {
                            Id = 46,
                            BrandId = 8,
                            CategoryId = 8,
                            Description = "Portable speaker",
                            ImageUrl = "/images/jblbb3.jpg",
                            Name = "JBL Boombox 3",
                            Price = 8999000m
                        },
                        new
                        {
                            Id = 47,
                            BrandId = 6,
                            CategoryId = 8,
                            Description = "Good Bluetooth speaker",
                            ImageUrl = "/images/sonyultpower.jpg",
                            Name = "Sony ULT Power Sound",
                            Price = 4999000m
                        },
                        new
                        {
                            Id = 48,
                            BrandId = 9,
                            CategoryId = 8,
                            Description = "Excellent portable speaker",
                            ImageUrl = "/images/scmotion300.jpg",
                            Name = "Soundcore Motion 300",
                            Price = 3999000m
                        },
                        new
                        {
                            Id = 49,
                            BrandId = 1,
                            CategoryId = 8,
                            Description = "Smart speaker",
                            ImageUrl = "/images/homepadmini.jpg",
                            Name = "Apple HomePod Mini",
                            Price = 1999000m
                        },
                        new
                        {
                            Id = 50,
                            BrandId = 2,
                            CategoryId = 8,
                            Description = "Smart speaker",
                            ImageUrl = "/images/galaxyhome.jpg",
                            Name = "Samsung Galaxy Home",
                            Price = 2999000m
                        });
                });

            modelBuilder.Entity("HDKmall.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("HDKmall.Models.ProductSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSpecifications");
                });

            modelBuilder.Entity("HDKmall.Models.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = "256GB",
                            Color = "Black",
                            ImageUrl = "/images/iphone15promax-black.jpg",
                            Price = 29999000m,
                            ProductId = 1,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            Capacity = "512GB",
                            Color = "Black",
                            ImageUrl = "/images/iphone15promax-black-512.jpg",
                            Price = 33999000m,
                            ProductId = 1,
                            Stock = 15
                        },
                        new
                        {
                            Id = 3,
                            Capacity = "1TB",
                            Color = "Black",
                            ImageUrl = "/images/iphone15promax-black-1tb.jpg",
                            Price = 37999000m,
                            ProductId = 1,
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            Capacity = "256GB",
                            Color = "Gold",
                            ImageUrl = "/images/iphone15promax-gold.jpg",
                            Price = 29999000m,
                            ProductId = 1,
                            Stock = 18
                        },
                        new
                        {
                            Id = 5,
                            Capacity = "512GB",
                            Color = "Gold",
                            ImageUrl = "/images/iphone15promax-gold-512.jpg",
                            Price = 33999000m,
                            ProductId = 1,
                            Stock = 12
                        },
                        new
                        {
                            Id = 6,
                            Capacity = "256GB",
                            Color = "Titanium",
                            ImageUrl = "/images/iphone15promax-titanium.jpg",
                            Price = 30999000m,
                            ProductId = 1,
                            Stock = 16
                        },
                        new
                        {
                            Id = 7,
                            Capacity = "512GB",
                            Color = "Titanium",
                            ImageUrl = "/images/iphone15promax-titanium-512.jpg",
                            Price = 34999000m,
                            ProductId = 1,
                            Stock = 14
                        },
                        new
                        {
                            Id = 8,
                            Capacity = "128GB",
                            Color = "Black",
                            ImageUrl = "/images/iphone15pro-black.jpg",
                            Price = 24999000m,
                            ProductId = 2,
                            Stock = 25
                        },
                        new
                        {
                            Id = 9,
                            Capacity = "256GB",
                            Color = "Black",
                            ImageUrl = "/images/iphone15pro-black-256.jpg",
                            Price = 27999000m,
                            ProductId = 2,
                            Stock = 20
                        },
                        new
                        {
                            Id = 10,
                            Capacity = "512GB",
                            Color = "Black",
                            ImageUrl = "/images/iphone15pro-black-512.jpg",
                            Price = 31999000m,
                            ProductId = 2,
                            Stock = 15
                        },
                        new
                        {
                            Id = 11,
                            Capacity = "128GB",
                            Color = "Blue",
                            ImageUrl = "/images/iphone15pro-blue.jpg",
                            Price = 24999000m,
                            ProductId = 2,
                            Stock = 22
                        },
                        new
                        {
                            Id = 12,
                            Capacity = "256GB",
                            Color = "Blue",
                            ImageUrl = "/images/iphone15pro-blue-256.jpg",
                            Price = 27999000m,
                            ProductId = 2,
                            Stock = 18
                        },
                        new
                        {
                            Id = 13,
                            Capacity = "128GB",
                            Color = "White",
                            ImageUrl = "/images/iphone15pro-white.jpg",
                            Price = 24999000m,
                            ProductId = 2,
                            Stock = 20
                        },
                        new
                        {
                            Id = 14,
                            Capacity = "256GB",
                            Color = "Black",
                            ImageUrl = "/images/s24ultra-black.jpg",
                            Price = 28999000m,
                            ProductId = 6,
                            Stock = 20
                        },
                        new
                        {
                            Id = 15,
                            Capacity = "512GB",
                            Color = "Black",
                            ImageUrl = "/images/s24ultra-black-512.jpg",
                            Price = 32999000m,
                            ProductId = 6,
                            Stock = 15
                        },
                        new
                        {
                            Id = 16,
                            Capacity = "256GB",
                            Color = "Titanium Gray",
                            ImageUrl = "/images/s24ultra-gray.jpg",
                            Price = 28999000m,
                            ProductId = 6,
                            Stock = 18
                        },
                        new
                        {
                            Id = 17,
                            Capacity = "512GB",
                            Color = "Titanium Gray",
                            ImageUrl = "/images/s24ultra-gray-512.jpg",
                            Price = 32999000m,
                            ProductId = 6,
                            Stock = 14
                        },
                        new
                        {
                            Id = 18,
                            Capacity = "256GB",
                            Color = "Titanium White",
                            ImageUrl = "/images/s24ultra-white.jpg",
                            Price = 28999000m,
                            ProductId = 6,
                            Stock = 16
                        },
                        new
                        {
                            Id = 19,
                            Capacity = "512GB",
                            Color = "Black",
                            ImageUrl = "/images/xiaomi14ultra-black.jpg",
                            Price = 21999000m,
                            ProductId = 11,
                            Stock = 22
                        },
                        new
                        {
                            Id = 20,
                            Capacity = "1TB",
                            Color = "Black",
                            ImageUrl = "/images/xiaomi14ultra-black-1tb.jpg",
                            Price = 24999000m,
                            ProductId = 11,
                            Stock = 18
                        },
                        new
                        {
                            Id = 21,
                            Capacity = "512GB",
                            Color = "White",
                            ImageUrl = "/images/xiaomi14ultra-white.jpg",
                            Price = 21999000m,
                            ProductId = 11,
                            Stock = 20
                        },
                        new
                        {
                            Id = 22,
                            Capacity = "512GB",
                            Color = "Blue",
                            ImageUrl = "/images/xiaomi14ultra-blue.jpg",
                            Price = 21999000m,
                            ProductId = 11,
                            Stock = 19
                        },
                        new
                        {
                            Id = 23,
                            Capacity = "AirPods",
                            Color = "White",
                            ImageUrl = "/images/airpods-white.jpg",
                            Price = 5999000m,
                            ProductId = 31,
                            Stock = 50
                        },
                        new
                        {
                            Id = 24,
                            Capacity = "AirPods",
                            Color = "Midnight",
                            ImageUrl = "/images/airpods-midnight.jpg",
                            Price = 5999000m,
                            ProductId = 31,
                            Stock = 45
                        },
                        new
                        {
                            Id = 25,
                            Capacity = "512GB",
                            Color = "Silver",
                            ImageUrl = "/images/mbpro-silver-512.jpg",
                            Price = 69999000m,
                            ProductId = 28,
                            Stock = 8
                        },
                        new
                        {
                            Id = 26,
                            Capacity = "1TB",
                            Color = "Silver",
                            ImageUrl = "/images/mbpro-silver-1tb.jpg",
                            Price = 79999000m,
                            ProductId = 28,
                            Stock = 5
                        },
                        new
                        {
                            Id = 27,
                            Capacity = "512GB",
                            Color = "Space Black",
                            ImageUrl = "/images/mbpro-black-512.jpg",
                            Price = 69999000m,
                            ProductId = 28,
                            Stock = 7
                        },
                        new
                        {
                            Id = 28,
                            Capacity = "1TB",
                            Color = "Space Black",
                            ImageUrl = "/images/mbpro-black-1tb.jpg",
                            Price = 79999000m,
                            ProductId = 28,
                            Stock = 4
                        },
                        new
                        {
                            Id = 29,
                            Capacity = "256GB",
                            Color = "Silver",
                            ImageUrl = "/images/ipadpro-silver-256.jpg",
                            Price = 27999000m,
                            ProductId = 26,
                            Stock = 12
                        },
                        new
                        {
                            Id = 30,
                            Capacity = "512GB",
                            Color = "Silver",
                            ImageUrl = "/images/ipadpro-silver-512.jpg",
                            Price = 31999000m,
                            ProductId = 26,
                            Stock = 8
                        },
                        new
                        {
                            Id = 31,
                            Capacity = "256GB",
                            Color = "Space Black",
                            ImageUrl = "/images/ipadpro-black-256.jpg",
                            Price = 27999000m,
                            ProductId = 26,
                            Stock = 10
                        },
                        new
                        {
                            Id = 32,
                            Capacity = "1 Size",
                            Color = "Black",
                            ImageUrl = "/images/wh1000xm5-black.jpg",
                            Price = 7999000m,
                            ProductId = 34,
                            Stock = 25
                        },
                        new
                        {
                            Id = 33,
                            Capacity = "1 Size",
                            Color = "Silver",
                            ImageUrl = "/images/wh1000xm5-silver.jpg",
                            Price = 7999000m,
                            ProductId = 34,
                            Stock = 20
                        },
                        new
                        {
                            Id = 34,
                            Capacity = "40mm",
                            Color = "Titanium",
                            ImageUrl = "/images/watchultra-40mm.jpg",
                            Price = 12999000m,
                            ProductId = 36,
                            Stock = 15
                        },
                        new
                        {
                            Id = 35,
                            Capacity = "46mm",
                            Color = "Titanium",
                            ImageUrl = "/images/watchultra-46mm.jpg",
                            Price = 12999000m,
                            ProductId = 36,
                            Stock = 13
                        },
                        new
                        {
                            Id = 36,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/iphone15.jpg",
                            Price = 19999000m,
                            ProductId = 3,
                            Stock = 23
                        },
                        new
                        {
                            Id = 37,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/iphone14pro.jpg",
                            Price = 21999000m,
                            ProductId = 4,
                            Stock = 24
                        },
                        new
                        {
                            Id = 38,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/iphonese.jpg",
                            Price = 12999000m,
                            ProductId = 5,
                            Stock = 25
                        },
                        new
                        {
                            Id = 39,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/s24.jpg",
                            Price = 22999000m,
                            ProductId = 7,
                            Stock = 27
                        },
                        new
                        {
                            Id = 40,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/a55.jpg",
                            Price = 10999000m,
                            ProductId = 8,
                            Stock = 28
                        },
                        new
                        {
                            Id = 41,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/zfold5.jpg",
                            Price = 39999000m,
                            ProductId = 9,
                            Stock = 29
                        },
                        new
                        {
                            Id = 42,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/tabs9.jpg",
                            Price = 18999000m,
                            ProductId = 10,
                            Stock = 20
                        },
                        new
                        {
                            Id = 43,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/xiaomi14.jpg",
                            Price = 17999000m,
                            ProductId = 12,
                            Stock = 22
                        },
                        new
                        {
                            Id = 44,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/redminote13.jpg",
                            Price = 8999000m,
                            ProductId = 13,
                            Stock = 23
                        },
                        new
                        {
                            Id = 45,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/xiaomipad6.jpg",
                            Price = 15999000m,
                            ProductId = 14,
                            Stock = 24
                        },
                        new
                        {
                            Id = 46,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/xiaomi13tpro.jpg",
                            Price = 19999000m,
                            ProductId = 15,
                            Stock = 25
                        },
                        new
                        {
                            Id = 47,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/findx7ultra.jpg",
                            Price = 27999000m,
                            ProductId = 16,
                            Stock = 26
                        },
                        new
                        {
                            Id = 48,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/findx7.jpg",
                            Price = 23999000m,
                            ProductId = 17,
                            Stock = 27
                        },
                        new
                        {
                            Id = 49,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/reno11.jpg",
                            Price = 12999000m,
                            ProductId = 18,
                            Stock = 28
                        },
                        new
                        {
                            Id = 50,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/a79.jpg",
                            Price = 6999000m,
                            ProductId = 19,
                            Stock = 29
                        },
                        new
                        {
                            Id = 51,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/opad2.jpg",
                            Price = 12999000m,
                            ProductId = 20,
                            Stock = 20
                        },
                        new
                        {
                            Id = 52,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/x100pro.jpg",
                            Price = 25999000m,
                            ProductId = 21,
                            Stock = 21
                        },
                        new
                        {
                            Id = 53,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/x100.jpg",
                            Price = 21999000m,
                            ProductId = 22,
                            Stock = 22
                        },
                        new
                        {
                            Id = 54,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/v40.jpg",
                            Price = 13999000m,
                            ProductId = 23,
                            Stock = 23
                        },
                        new
                        {
                            Id = 55,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/y100.jpg",
                            Price = 6999000m,
                            ProductId = 24,
                            Stock = 24
                        },
                        new
                        {
                            Id = 56,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/vpad.jpg",
                            Price = 13999000m,
                            ProductId = 25,
                            Stock = 25
                        },
                        new
                        {
                            Id = 57,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/ipadair.jpg",
                            Price = 18999000m,
                            ProductId = 27,
                            Stock = 27
                        },
                        new
                        {
                            Id = 58,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/mbairrm3.jpg",
                            Price = 42999000m,
                            ProductId = 29,
                            Stock = 29
                        },
                        new
                        {
                            Id = 59,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/mbatrm2.jpg",
                            Price = 37999000m,
                            ProductId = 30,
                            Stock = 20
                        },
                        new
                        {
                            Id = 60,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/airpodsmax.jpg",
                            Price = 18999000m,
                            ProductId = 32,
                            Stock = 22
                        },
                        new
                        {
                            Id = 61,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/galaxybuds2pro.jpg",
                            Price = 4999000m,
                            ProductId = 33,
                            Stock = 23
                        },
                        new
                        {
                            Id = 62,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/jbllivepro2.jpg",
                            Price = 5999000m,
                            ProductId = 35,
                            Stock = 25
                        },
                        new
                        {
                            Id = 63,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/watchs9.jpg",
                            Price = 8999000m,
                            ProductId = 37,
                            Stock = 27
                        },
                        new
                        {
                            Id = 64,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/watch6pro.jpg",
                            Price = 8999000m,
                            ProductId = 38,
                            Stock = 28
                        },
                        new
                        {
                            Id = 65,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/watchs3.jpg",
                            Price = 4999000m,
                            ProductId = 39,
                            Stock = 29
                        },
                        new
                        {
                            Id = 66,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/watch3.jpg",
                            Price = 3999000m,
                            ProductId = 40,
                            Stock = 20
                        },
                        new
                        {
                            Id = 67,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/a7rv.jpg",
                            Price = 54999000m,
                            ProductId = 41,
                            Stock = 21
                        },
                        new
                        {
                            Id = 68,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/a6700.jpg",
                            Price = 24999000m,
                            ProductId = 42,
                            Stock = 22
                        },
                        new
                        {
                            Id = 69,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/s24cam.jpg",
                            Price = 22999000m,
                            ProductId = 43,
                            Stock = 23
                        },
                        new
                        {
                            Id = 70,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/djimini4pro.jpg",
                            Price = 18999000m,
                            ProductId = 44,
                            Stock = 24
                        },
                        new
                        {
                            Id = 71,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/ip15cam.jpg",
                            Price = 29999000m,
                            ProductId = 45,
                            Stock = 25
                        },
                        new
                        {
                            Id = 72,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/jblbb3.jpg",
                            Price = 8999000m,
                            ProductId = 46,
                            Stock = 26
                        },
                        new
                        {
                            Id = 73,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/sonyultpower.jpg",
                            Price = 4999000m,
                            ProductId = 47,
                            Stock = 27
                        },
                        new
                        {
                            Id = 74,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/scmotion300.jpg",
                            Price = 3999000m,
                            ProductId = 48,
                            Stock = 28
                        },
                        new
                        {
                            Id = 75,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/homepadmini.jpg",
                            Price = 1999000m,
                            ProductId = 49,
                            Stock = 29
                        },
                        new
                        {
                            Id = 76,
                            Capacity = "Default",
                            Color = "Standard",
                            ImageUrl = "/images/galaxyhome.jpg",
                            Price = 2999000m,
                            ProductId = 50,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("HDKmall.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HDKmall.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("HDKmall.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("HDKmall.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@hdk.com",
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "admin123",
                            PhoneNumber = "0123456789",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nguyen.van.a@email.com",
                            FullName = "Nguyễn Văn A",
                            IsActive = true,
                            PasswordHash = "password123",
                            PhoneNumber = "0912345678",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tran.thi.b@email.com",
                            FullName = "Trần Thị B",
                            IsActive = true,
                            PasswordHash = "password123",
                            PhoneNumber = "0987654321",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "le.van.c@email.com",
                            FullName = "Lê Văn C",
                            IsActive = true,
                            PasswordHash = "password123",
                            PhoneNumber = "0912111111",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pham.thi.d@email.com",
                            FullName = "Phạm Thị D",
                            IsActive = true,
                            PasswordHash = "password123",
                            PhoneNumber = "0912222222",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hoang.van.e@email.com",
                            FullName = "Hoàng Văn E",
                            IsActive = true,
                            PasswordHash = "password123",
                            PhoneNumber = "0912333333",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "do.thi.f@email.com",
                            FullName = "Đỗ Thị F",
                            IsActive = true,
                            PasswordHash = "password123",
                            PhoneNumber = "0912444444",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vu.van.g@email.com",
                            FullName = "Vũ Văn G",
                            IsActive = true,
                            PasswordHash = "password123",
                            PhoneNumber = "0912555555",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dinh.thi.h@email.com",
                            FullName = "Đinh Thị H",
                            IsActive = true,
                            PasswordHash = "password123",
                            PhoneNumber = "0912666666",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bui.van.i@email.com",
                            FullName = "Bùi Văn I",
                            IsActive = true,
                            PasswordHash = "password123",
                            PhoneNumber = "0912777777",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 11,
                            CreatedAt = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cao.thi.k@email.com",
                            FullName = "Cao Thị K",
                            IsActive = true,
                            PasswordHash = "password123",
                            PhoneNumber = "0912888888",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("HDKmall.Models.UserAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("HDKmall.Models.CartItem", b =>
                {
                    b.HasOne("HDKmall.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HDKmall.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("HDKmall.Models.Order", b =>
                {
                    b.HasOne("HDKmall.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HDKmall.Models.OrderDetail", b =>
                {
                    b.HasOne("HDKmall.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HDKmall.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HDKmall.Models.Product", b =>
                {
                    b.HasOne("HDKmall.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("HDKmall.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HDKmall.Models.ProductImage", b =>
                {
                    b.HasOne("HDKmall.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HDKmall.Models.ProductSpecification", b =>
                {
                    b.HasOne("HDKmall.Models.Product", "Product")
                        .WithMany("Specifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HDKmall.Models.ProductVariant", b =>
                {
                    b.HasOne("HDKmall.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HDKmall.Models.Review", b =>
                {
                    b.HasOne("HDKmall.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HDKmall.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HDKmall.Models.ShoppingCart", b =>
                {
                    b.HasOne("HDKmall.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HDKmall.Models.User", b =>
                {
                    b.HasOne("HDKmall.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HDKmall.Models.UserAddress", b =>
                {
                    b.HasOne("HDKmall.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HDKmall.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HDKmall.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HDKmall.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("HDKmall.Models.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Specifications");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("HDKmall.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HDKmall.Models.ShoppingCart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HDKmall.Models.User", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
