#pragma checksum "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "71ec8be55e9a63049da6e88b97744b90f9769c68"
// <auto-generated/>
#pragma warning disable 1591
namespace Razor
{
    #line hidden
#nullable restore
#line 1 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\_ViewImports.cshtml"
using HDKmall;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\_ViewImports.cshtml"
using HDKmall.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\_ViewImports.cshtml"
using HDKmall.ViewModels;

#line default
#line hidden
#nullable disable
    public class Template
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 1 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
Write(model);

#line default
#line hidden
#nullable disable
            WriteLiteral(" IEnumerable<HDKmall.Models.User>\r\n");
#nullable restore
#line 2 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
  
    ViewData["Title"] = "Quản lý người dùng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n    <h2 class=\"fw-bold mb-0\">👥 Quản lý Người Dùng</h2>\r\n</div>\r\n\r\n");
#nullable restore
#line 11 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
 if (TempData["Success"] != null)
{

#line default
#line hidden
#nullable disable
            WriteLiteral("    <div class=\"alert alert-success alert-dismissible fade show shadow-sm border-0 rounded-3\" role=\"alert\">\r\n        <i class=\"bi bi-check-circle-fill me-2\"></i> ");
#nullable restore
#line 14 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                                Write(TempData["Success"]);

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n    </div>\r\n");
#nullable restore
#line 17 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
}

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<!-- Summary Stats -->\r\n");
#nullable restore
#line 20 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
 if (Model != null && Model.Any())
{
    var totalUsers  = Model.Count();
    var activeUsers = Model.Count(u => u.IsActive);
    var lockedUsers = Model.Count(u => !u.IsActive);
    var adminCount  = Model.Count(u => u.Role?.RoleName == "Admin");

#line default
#line hidden
#nullable disable
            WriteLiteral(@"    <div class=""row g-3 mb-4"">
        <div class=""col-6 col-lg-3"">
            <div class=""card border-0 shadow-sm rounded-4 h-100"">
                <div class=""card-body d-flex align-items-center gap-3 py-3"">
                    <div class=""rounded-3 bg-primary bg-opacity-10 d-flex align-items-center justify-content-center"" style=""width:46px;height:46px;flex-shrink:0;"">
                        <i class=""bi bi-people text-primary fs-5""></i>
                    </div>
                    <div>
                        <div class=""text-muted small"">Tổng người dùng</div>
                        <div class=""fw-bold fs-5"">");
#nullable restore
#line 35 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                             Write(totalUsers);

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-6 col-lg-3"">
            <div class=""card border-0 shadow-sm rounded-4 h-100"">
                <div class=""card-body d-flex align-items-center gap-3 py-3"">
                    <div class=""rounded-3 bg-success bg-opacity-10 d-flex align-items-center justify-content-center"" style=""width:46px;height:46px;flex-shrink:0;"">
                        <i class=""bi bi-person-check text-success fs-5""></i>
                    </div>
                    <div>
                        <div class=""text-muted small"">Hoạt động</div>
                        <div class=""fw-bold fs-5"">");
#nullable restore
#line 48 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                             Write(activeUsers);

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-6 col-lg-3"">
            <div class=""card border-0 shadow-sm rounded-4 h-100"">
                <div class=""card-body d-flex align-items-center gap-3 py-3"">
                    <div class=""rounded-3 bg-danger bg-opacity-10 d-flex align-items-center justify-content-center"" style=""width:46px;height:46px;flex-shrink:0;"">
                        <i class=""bi bi-person-x text-danger fs-5""></i>
                    </div>
                    <div>
                        <div class=""text-muted small"">Đã khóa</div>
                        <div class=""fw-bold fs-5"">");
#nullable restore
#line 61 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                             Write(lockedUsers);

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-6 col-lg-3"">
            <div class=""card border-0 shadow-sm rounded-4 h-100"">
                <div class=""card-body d-flex align-items-center gap-3 py-3"">
                    <div class=""rounded-3 bg-warning bg-opacity-10 d-flex align-items-center justify-content-center"" style=""width:46px;height:46px;flex-shrink:0;"">
                        <i class=""bi bi-shield-check text-warning fs-5""></i>
                    </div>
                    <div>
                        <div class=""text-muted small"">Quản trị viên</div>
                        <div class=""fw-bold fs-5"">");
#nullable restore
#line 74 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                             Write(adminCount);

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");
#nullable restore
#line 80 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
}

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
<div class=""card shadow-sm border-0 rounded-4 mb-4"">
    <div class=""card-header bg-white border-bottom-0 pt-4 pb-3 px-4 d-flex justify-content-between align-items-center"">
        <h5 class=""mb-0 fw-bold text-secondary"">Tất cả người dùng</h5>
        <form asp-area=""Admin"" asp-controller=""User"" asp-action=""Index"" method=""get"" class=""d-flex"" style=""width: 320px;"">
            <div class=""input-group"">
                <span class=""input-group-text bg-light border-end-0 rounded-start-pill""><i class=""bi bi-search text-muted""></i></span>
                <input type=""text"" name=""q"" class=""form-control bg-light border-start-0 rounded-end-pill focus-ring focus-ring-danger"" placeholder=""Tìm tên, email..."" />
            </div>
        </form>
    </div>

    <div class=""card-body p-0"">
        <div class=""table-responsive"">
            <table class=""table table-hover align-middle mb-0"">
                <thead class=""table-light text-secondary"">
                    <tr>
                        <th cl");
            WriteLiteral(@"ass=""px-4 py-3 border-0"">ID</th>
                        <th class=""py-3 border-0"">Người dùng</th>
                        <th class=""py-3 border-0"">Email</th>
                        <th class=""py-3 border-0"">Điện thoại</th>
                        <th class=""py-3 border-0"">Vai trò</th>
                        <th class=""py-3 border-0"">Trạng thái</th>
                        <th class=""px-4 py-3 border-0"">Ngày tham gia</th>
                    </tr>
                </thead>
                <tbody class=""border-top-0"">
");
#nullable restore
#line 108 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                     if (Model != null && Model.Any())
                    {
                        int i = 1;
                        foreach (var user in Model)
                        {
                            var isAdmin = user.Role?.RoleName == "Admin";
                            var avatarColors = new[] {
                                "bg-primary", "bg-success", "bg-info", "bg-warning", "bg-danger",
                                "bg-secondary", "bg-dark"
                            };
                            var avatarColor = avatarColors[user.UserId % avatarColors.Length];

#line default
#line hidden
#nullable disable
            WriteLiteral("                            <tr>\r\n                                <td class=\"px-4 text-muted fw-medium\">#");
#nullable restore
#line 120 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                                                   Write(i++);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                                <td>\r\n                                    <div class=\"d-flex align-items-center gap-3\">\r\n                                        <div");
            BeginWriteAttribute("class", " class=\"", 6233, "\"", 6349, 8);
            WriteAttributeValue("", 6241, "rounded-circle", 6241, 14, true);
#nullable restore
#line 123 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
WriteAttributeValue(" ", 6255, avatarColor, 6256, 12, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue(" ", 6268, "bg-opacity-15", 6269, 14, true);
            WriteAttributeValue(" ", 6282, "d-flex", 6283, 7, true);
            WriteAttributeValue(" ", 6289, "align-items-center", 6290, 19, true);
            WriteAttributeValue(" ", 6308, "justify-content-center", 6309, 23, true);
            WriteAttributeValue(" ", 6331, "fw-bold", 6332, 8, true);
            WriteAttributeValue(" ", 6339, "text-dark", 6340, 10, true);
            EndWriteAttribute();
            WriteLiteral("\r\n                                             style=\"width:38px;height:38px;font-size:15px;flex-shrink:0;\">\r\n                                             ");
#nullable restore
#line 125 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                         Write((user.FullName ?? "?").Substring(0, 1).ToUpper());

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                        </div>\r\n                                        <div>\r\n                                            <div class=\"fw-semibold text-dark\" style=\"font-size:14px;\">");
#nullable restore
#line 128 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                                                                                  Write(user.FullName);

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n                                            <div class=\"text-muted\" style=\"font-size:11px;\">ID: ");
#nullable restore
#line 129 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                                                                           Write(user.UserId);

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n                                        </div>\r\n                                    </div>\r\n                                </td>\r\n                                <td>\r\n                                    <a");
            BeginWriteAttribute("href", " href=\"", 7101, "\"", 7126, 2);
            WriteAttributeValue("", 7108, "mailto:", 7108, 7, true);
#nullable restore
#line 134 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
WriteAttributeValue("", 7115, user.Email, 7115, 11, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" class=\"text-decoration-none text-dark small\">\r\n                                        <i class=\"bi bi-envelope me-1 text-muted\"></i>");
#nullable restore
#line 135 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                                                                 Write(user.Email);

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                                    </a>
                                </td>
                                <td>
                                    <form asp-action=""UpdateRole"" method=""post"" class=""d-flex align-items-center"">
                                        ");
#nullable restore
#line 140 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                   Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                        <input type=\"hidden\" name=\"id\"");
            BeginWriteAttribute("value", " value=\"", 7645, "\"", 7665, 1);
#nullable restore
#line 141 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
WriteAttributeValue("", 7653, user.UserId, 7653, 12, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" />\r\n                                        <select name=\"roleId\" class=\"form-select form-select-sm border-0 bg-light rounded-pill px-3\" onchange=\"this.form.submit()\" style=\"font-size:12px; width:120px;\">\r\n");
#nullable restore
#line 143 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                             foreach (var role in (IEnumerable<HDKmall.Models.Role>)ViewBag.Roles)
                                            {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                                <option");
            BeginWriteAttribute("value", " value=\"", 8091, "\"", 8111, 1);
#nullable restore
#line 145 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
WriteAttributeValue("", 8099, role.RoleId, 8099, 12, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            BeginWriteAttribute("selected", " selected=\"", 8112, "\"", 8152, 1);
#nullable restore
#line 145 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
WriteAttributeValue("", 8123, user.RoleId == role.RoleId, 8123, 29, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">");
#nullable restore
#line 145 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                                                                                                 Write(role.RoleName);

#line default
#line hidden
#nullable disable
            WriteLiteral("</option>\r\n");
#nullable restore
#line 146 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                            }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                                        </select>
                                    </form>
                                </td>
                                <td>
                                    <form asp-action=""ToggleStatus"" method=""post"">
                                        ");
#nullable restore
#line 152 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                   Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                        <input type=\"hidden\" name=\"id\"");
            BeginWriteAttribute("value", " value=\"", 8619, "\"", 8639, 1);
#nullable restore
#line 153 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
WriteAttributeValue("", 8627, user.UserId, 8627, 12, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" />\r\n");
#nullable restore
#line 154 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                         if (user.IsActive)
                                        {

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                                            <button type=""submit"" class=""btn btn-sm btn-outline-success rounded-pill px-3 border-success-subtle"" style=""font-size:11px;"">
                                                <i class=""bi bi-check-circle-fill me-1""></i>Hoạt động
                                            </button>
");
#nullable restore
#line 159 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                        }
                                        else
                                        {

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                                            <button type=""submit"" class=""btn btn-sm btn-outline-danger rounded-pill px-3 border-danger-subtle"" style=""font-size:11px;"">
                                                <i class=""bi bi-lock-fill me-1""></i>Đã khóa
                                            </button>
");
#nullable restore
#line 165 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                        }

#line default
#line hidden
#nullable disable
            WriteLiteral("                                    </form>\r\n                                </td>\r\n                                <td class=\"px-4\">\r\n                                    <div class=\"fw-medium small\">");
#nullable restore
#line 169 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                                            Write(user.CreatedAt.ToString("dd/MM/yyyy"));

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n                                    <div class=\"text-muted\" style=\"font-size:11px;\">");
#nullable restore
#line 170 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                                                               Write(user.CreatedAt.ToString("HH:mm"));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</div>
                                </td>
                                <td class=""px-4 text-end"">
                                    <div class=""dropdown"">
                                        <button class=""btn btn-link text-muted p-0"" data-bs-toggle=""dropdown"">
                                            <i class=""bi bi-three-dots-vertical""></i>
                                        </button>
                                        <ul class=""dropdown-menu dropdown-menu-end shadow-sm border-0 rounded-3"">
                                            <li><a class=""dropdown-item small"" href=""#""><i class=""bi bi-eye me-2""></i>Xem chi tiết</a></li>
                                            <li><a class=""dropdown-item small"" href=""#""><i class=""bi bi-pencil me-2""></i>Sửa thông tin</a></li>
                                            <li><hr class=""dropdown-divider""></li>
                                            <li>
                                                <form asp-action=""Toggle");
            WriteLiteral("Status\" method=\"post\">\r\n                                                    ");
#nullable restore
#line 183 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                               Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                                    <input type=\"hidden\" name=\"id\"");
            BeginWriteAttribute("value", " value=\"", 11141, "\"", 11161, 1);
#nullable restore
#line 184 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
WriteAttributeValue("", 11149, user.UserId, 11149, 12, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" />\r\n                                                    <button type=\"submit\" class=\"dropdown-item small text-danger\">\r\n                                                        <i");
            BeginWriteAttribute("class", " class=\"", 11341, "\"", 11399, 3);
            WriteAttributeValue("", 11349, "bi", 11349, 2, true);
#nullable restore
#line 186 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
WriteAttributeValue(" ", 11351, user.IsActive ? "bi-lock" : "bi-unlock", 11352, 42, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue(" ", 11394, "me-2", 11395, 5, true);
            EndWriteAttribute();
            WriteLiteral("></i>");
#nullable restore
#line 186 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                                                                                                      Write(user.IsActive ? "Khóa tài khoản" : "Mở khóa");

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                                                    </button>
                                                </form>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
");
#nullable restore
#line 194 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                        }
                    }
                    else
                    {

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                        <tr>
                            <td colspan=""7"" class=""text-center py-5 text-muted"">
                                <div class=""fs-1 mb-3"">👥</div>
                                <h5>Chưa có người dùng nào</h5>
                                <p>Người dùng sẽ xuất hiện tại đây sau khi đăng ký.</p>
                            </td>
                        </tr>
");
#nullable restore
#line 205 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                    }

#line default
#line hidden
#nullable disable
            WriteLiteral("                </tbody>\r\n            </table>\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"card-footer bg-white border-top p-3 d-flex justify-content-between align-items-center rounded-bottom-4\">\r\n        <span class=\"text-muted small\">Hiển thị ");
#nullable restore
#line 212 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Areas\Admin\Views\User\Index.cshtml"
                                            Write(Model?.Count() ?? 0);

#line default
#line hidden
#nullable disable
            WriteLiteral(" người dùng</span>\r\n    </div>\r\n</div>\r\n");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
