#pragma checksum "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "742441de5ff74fdc1c4e3081b3bd7f7d760303e0"
// <auto-generated/>
#pragma warning disable 1591
namespace Razor
{
    #line hidden
#nullable restore
#line 1 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\_ViewImports.cshtml"
using HDKmall;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\_ViewImports.cshtml"
using HDKmall.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\_ViewImports.cshtml"
using HDKmall.ViewModels;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
using HDKmall.Helpers;

#line default
#line hidden
#nullable disable
    public class Template
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 1 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
Write(model);

#line default
#line hidden
#nullable disable
            WriteLiteral(" HDKmall.Models.ShoppingCart\r\n");
#nullable restore
#line 3 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
  
    ViewData["Title"] = "Giỏ hàng";

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
<style>
    .cps-bg { background-color: #f4f6f8; }
    .cps-cart-container { max-width: 680px; margin: 0 auto; }
    .cps-title { font-size: 18px; font-weight: 700; color: #333; }
    .cps-card { background: #fff; border-radius: 10px; box-shadow: 0 1px 4px rgba(0,0,0,0.1); border: none; }
    .cps-text-red { color: #d70018 !important; }
    .cps-bg-red { background-color: #d70018 !important; color: #fff !important; pointer-events: auto; border: none; }
    .cps-bg-red:hover { background-color: #bd0015 !important; color: #fff; }
    .cps-product-name { font-size: 15px; font-weight: 600; color: #333; text-decoration: none; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; line-height: 1.4; }
    .cps-product-name:hover { color: #d70018; }
    .cps-qty-btn { width: 32px; height: 32px; background: #fff; border: 1px solid #e5e5e5; display: flex; align-items: center; justify-content: center; font-size: 16px; cursor: pointer; color: #333; transition: all 0.2s; }");
            WriteLiteral(@"
    .cps-qty-btn:hover { background: #f0f0f0; }
    .cps-qty-input { width: 40px; height: 32px; text-align: center; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5; border-left: none; border-right: none; font-size: 14px; outline: none; }
    .cps-btn-delete { background: none; border: none; padding: 0; color: #999; cursor: pointer; transition: all 0.2s; }
    .cps-btn-delete:hover { color: #d70018; }
    .cps-total-group { font-size: 15px; color: #444; }
    .cps-fixed-bottom { position: sticky; bottom: 0; background: #fff; z-index: 1000; box-shadow: 0 -4px 15px rgba(0,0,0,0.05); }
    .cps-checkbox { width: 20px; height: 20px; accent-color: #d70018; cursor: pointer; flex-shrink: 0; }
    .cps-select-all-bar { background: #fff; border-radius: 10px; box-shadow: 0 1px 4px rgba(0,0,0,0.1); padding: 10px 16px; }
    .cps-item-subtotal { font-size: 14px; color: #d70018; font-weight: 600; white-space: nowrap; }
    
    /* Product Card Styles (Shared with Product Listing) */
    .pl-pro");
            WriteLiteral(@"duct-card { background:#fff; border-radius:10px; border:1.5px solid #f0f0f0; overflow:hidden; transition:all .2s; display:flex; flex-direction:column; }
    .pl-product-card:hover { border-color:#d70018; box-shadow:0 6px 18px rgba(215,0,24,.1); transform:translateY(-3px); }
    .pl-product-card .img-box { background:#fff; aspect-ratio:1/1; display:flex; align-items:center; justify-content:center; padding:12px; }
    .pl-product-card img { max-height:100%; object-fit:contain; transition:transform .2s; }
    .pl-product-card:hover img { transform:scale(1.05); }
    .pl-wishlist-btn { background:none; border:none; padding:0; cursor:pointer; color:#aaa; font-size:18px; transition:color .2s; display:flex; align-items:center; gap:4px; }
    .pl-wishlist-btn:hover, .pl-wishlist-btn.active { color:#d70018; }
    .text-truncate-2 { display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
</style>

<div class=""main-content cps-bg py-4 min-vh-100"">
    <div class=""contain");
            WriteLiteral(@"er cps-cart-container"">
        <!-- Header -->
        <div class=""d-flex align-items-center mb-3"">
            <a asp-controller=""Product"" asp-action=""Index"" class=""text-dark d-flex align-items-center text-decoration-none"" title=""Trở về"">
                <i class=""bi bi-chevron-left fw-bold""></i><span class=""ms-1 fw-bold"">Trở về</span>
            </a>
            <h1 class=""cps-title m-0 flex-grow-1 text-center pe-4"">Giỏ hàng của bạn</h1>
        </div>

");
#nullable restore
#line 49 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
         if (TempData["Error"] != null)
        {

#line default
#line hidden
#nullable disable
            WriteLiteral("            <div class=\"alert alert-danger alert-dismissible fade show mb-3\">");
#nullable restore
#line 51 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                        Write(TempData["Error"]);

#line default
#line hidden
#nullable disable
            WriteLiteral("<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button></div>\r\n");
#nullable restore
#line 52 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
        }

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n");
#nullable restore
#line 54 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
         if (Model != null && Model.Items.Any())
        {

#line default
#line hidden
#nullable disable
            WriteLiteral("            <form id=\"checkout-form\" asp-controller=\"Cart\" asp-action=\"ProceedToCheckout\" method=\"post\">\r\n                ");
#nullable restore
#line 57 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
           Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
            WriteLiteral(@"

                <!-- Select All Bar -->
                <div class=""cps-select-all-bar mb-2 d-flex align-items-center gap-2"">
                    <input type=""checkbox"" id=""select-all"" class=""cps-checkbox"" checked />
                    <label for=""select-all"" class=""mb-0 fw-semibold"" style=""cursor:pointer; font-size:14px;"">Chọn tất cả (");
#nullable restore
#line 62 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                                                                     Write(Model.Items.Count);

#line default
#line hidden
#nullable disable
            WriteLiteral(" sản phẩm)</label>\r\n                </div>\r\n\r\n                <!-- List Items -->\r\n                <div class=\"d-flex flex-column gap-3 mb-4\" id=\"cart-items-list\">\r\n");
#nullable restore
#line 67 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                     foreach (var item in Model.Items)
                    {
                        var itemPrice = item.Variant != null ? item.Variant.Price : item.Product.Price;
                        var variantLabel = (item.Variant != null)
                            ? string.Join(" / ", new[] { item.Variant.Color, item.Variant.ProductVersion?.Name }.Where(v => !string.IsNullOrEmpty(v)))
                            : "";

#line default
#line hidden
#nullable disable
            WriteLiteral("                        <div class=\"cps-card p-3 cart-item-row\" data-item-id=\"");
#nullable restore
#line 73 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                         Write(item.Id);

#line default
#line hidden
#nullable disable
            WriteLiteral("\" data-price=\"");
#nullable restore
#line 73 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                                               Write(itemPrice);

#line default
#line hidden
#nullable disable
            WriteLiteral("\">\r\n                            <div class=\"d-flex align-items-start gap-2\">\r\n                                <!-- Checkbox -->\r\n                                <input type=\"checkbox\" name=\"selectedItems\"");
            BeginWriteAttribute("value", " value=\"", 5376, "\"", 5392, 1);
#nullable restore
#line 76 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 5384, item.Id, 5384, 8, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" class=""cps-checkbox item-checkbox mt-1"" checked />

                                <!-- Product Image -->
                                <div style=""width: 90px; height: 90px; flex-shrink:0; display:flex; align-items:center; justify-content:center;"">
");
#nullable restore
#line 80 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                      
                                        string imgUrl = item.Variant?.ProductVersion?.ImageUrl ?? item.Product.ImageUrl;
                                    

#line default
#line hidden
#nullable disable
            WriteLiteral("                                    <img");
            BeginWriteAttribute("src", " src=\"", 5892, "\"", 5930, 1);
#nullable restore
#line 83 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 5898, ImageHelper.GetImageUrl(imgUrl), 5898, 32, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            BeginWriteAttribute("alt", " alt=\"", 5931, "\"", 5955, 1);
#nullable restore
#line 83 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 5937, item.Product.Name, 5937, 18, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" class=""img-fluid"" style=""max-height: 100%; object-fit: contain;"" onerror=""this.src='/img/default.png'"">
                                </div>

                                <!-- Product Info -->
                                <div class=""flex-grow-1 min-w-0"">
                                    <a asp-controller=""Product"" asp-action=""Detail""");
            BeginWriteAttribute("asp-route-id", " asp-route-id=\"", 6309, "\"", 6339, 1);
#nullable restore
#line 88 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 6324, item.ProductId, 6324, 15, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" class=\"cps-product-name mb-1 d-block\">");
#nullable restore
#line 88 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                                                                                                    Write(item.Product.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</a>\r\n");
#nullable restore
#line 89 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                     if (!string.IsNullOrEmpty(variantLabel))
                                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                        <div class=\"text-muted\" style=\"font-size:12px;\">");
#nullable restore
#line 91 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                                   Write(variantLabel);

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n");
#nullable restore
#line 92 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                    }

#line default
#line hidden
#nullable disable
            WriteLiteral("                                    <div class=\"cps-text-red fw-bold fs-6 mb-2\">");
#nullable restore
#line 93 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                           Write(itemPrice.ToString("N0"));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"₫</div>

                                    <div class=""d-flex align-items-center justify-content-between flex-wrap gap-2"">
                                        <!-- Quantity Stepper -->
                                        <div class=""d-flex rounded"" style=""overflow: hidden;"">
                                            <button class=""cps-qty-btn rounded-start"" type=""button""");
            BeginWriteAttribute("onclick", " onclick=\"", 7164, "\"", 7215, 5);
            WriteAttributeValue("", 7174, "updateQty(", 7174, 10, true);
#nullable restore
#line 98 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 7184, item.Id, 7184, 8, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 7192, ",", 7192, 1, true);
#nullable restore
#line 98 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue(" ", 7193, item.Quantity - 1, 7194, 20, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 7214, ")", 7214, 1, true);
            EndWriteAttribute();
            WriteLiteral(">−</button>\r\n                                            <input type=\"number\" class=\"cps-qty-input fw-medium text-dark bg-white qty-input\"");
            BeginWriteAttribute("id", " id=\"", 7354, "\"", 7371, 2);
            WriteAttributeValue("", 7359, "qty-", 7359, 4, true);
#nullable restore
#line 99 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 7363, item.Id, 7363, 8, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            BeginWriteAttribute("value", " value=\"", 7372, "\"", 7394, 1);
#nullable restore
#line 99 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 7380, item.Quantity, 7380, 14, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" min=\"1\" max=\"99\"");
            BeginWriteAttribute("onchange", " onchange=\"", 7412, "\"", 7454, 4);
            WriteAttributeValue("", 7423, "updateQty(", 7423, 10, true);
#nullable restore
#line 99 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 7433, item.Id, 7433, 8, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 7441, ",", 7441, 1, true);
            WriteAttributeValue(" ", 7442, "this.value)", 7443, 12, true);
            EndWriteAttribute();
            WriteLiteral(">\r\n                                            <button class=\"cps-qty-btn rounded-end\" type=\"button\"");
            BeginWriteAttribute("onclick", " onclick=\"", 7555, "\"", 7606, 5);
            WriteAttributeValue("", 7565, "updateQty(", 7565, 10, true);
#nullable restore
#line 100 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 7575, item.Id, 7575, 8, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 7583, ",", 7583, 1, true);
#nullable restore
#line 100 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue(" ", 7584, item.Quantity + 1, 7585, 20, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 7605, ")", 7605, 1, true);
            EndWriteAttribute();
            WriteLiteral(">+</button>\r\n                                        </div>\r\n\r\n                                        <!-- Item subtotal -->\r\n                                        <span class=\"cps-item-subtotal\"");
            BeginWriteAttribute("id", " id=\"", 7805, "\"", 7827, 2);
            WriteAttributeValue("", 7810, "subtotal-", 7810, 9, true);
#nullable restore
#line 104 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 7819, item.Id, 7819, 8, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">");
#nullable restore
#line 104 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                                           Write((itemPrice * item.Quantity).ToString("N0"));

#line default
#line hidden
#nullable disable
            WriteLiteral("₫</span>\r\n\r\n                                        <!-- Delete Button -->\r\n                                        <button type=\"button\" class=\"cps-btn-delete\" title=\"Xóa\"");
            BeginWriteAttribute("onclick", " onclick=\"", 8046, "\"", 8076, 3);
            WriteAttributeValue("", 8056, "removeItem(", 8056, 11, true);
#nullable restore
#line 107 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 8067, item.Id, 8067, 8, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 8075, ")", 8075, 1, true);
            EndWriteAttribute();
            WriteLiteral(@">
                                            <svg xmlns=""http://www.w3.org/2000/svg"" width=""18"" height=""18"" fill=""currentColor"" class=""bi bi-trash3"" viewBox=""0 0 16 16"">
                                                <path d=""M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5""/>
                                            </svg>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
");
#nullable restore
#line 116 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                    }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                </div>

                <!-- Total Bottom Bar -->
                <div class=""cps-card p-3 cps-fixed-bottom border-top-0 rounded-bottom-0 rounded-top-4"">
                    <div class=""d-flex justify-content-between align-items-center mb-2 cps-total-group"">
                        <span class=""fw-medium"">Đã chọn <span id=""selected-count"">");
#nullable restore
#line 122 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                             Write(Model.Items.Count);

#line default
#line hidden
#nullable disable
            WriteLiteral("</span> sản phẩm</span>\r\n                        <span class=\"fw-medium\" id=\"selected-qty-text\">(");
#nullable restore
#line 123 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                   Write(Model.Items.Sum(x => x.Quantity));

#line default
#line hidden
#nullable disable
            WriteLiteral(@" sản phẩm)</span>
                    </div>
                    <div class=""d-flex justify-content-between align-items-center mb-3"">
                        <span class=""fw-bold"">Tổng tiền</span>
                        <span class=""fs-5 fw-bold cps-text-red"" id=""total-amount"">");
#nullable restore
#line 127 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                             Write(Model.Items.Sum(x => (x.Variant != null ? x.Variant.Price : x.Product.Price) * x.Quantity).ToString("N0"));

#line default
#line hidden
#nullable disable
            WriteLiteral(@"₫</span>
                    </div>
                    <button type=""submit"" class=""btn w-100 py-3 fw-bold cps-bg-red text-uppercase rounded-3 shadow-sm d-block text-center"" id=""checkout-btn"">
                        Tiến hành đặt hàng
                    </button>
                </div>
            </form>
");
#nullable restore
#line 134 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
        }
        else
        {

#line default
#line hidden
#nullable disable
            WriteLiteral(@"            <div class=""cps-card p-5 text-center mt-4"">
                <div class=""mb-4"">
                    <svg xmlns=""http://www.w3.org/2000/svg"" width=""80"" height=""80"" fill=""#d70018"" class=""bi bi-cart-x"" viewBox=""0 0 16 16"">
                      <path d=""M7.354 5.646a.5.5 0 1 0-.708.708L7.793 7.5 6.646 8.646a.5.5 0 1 0 .708.708L8.5 8.207l1.146 1.147a.5.5 0 0 0 .708-.708L9.207 7.5l1.147-1.146a.5.5 0 0 0-.708-.708L8.5 6.793z""/>
                      <path d=""M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zm3.915 10L3.102 4h10.796l-1.313 7zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0""/>
                    </svg>
                </div>
                <h6 class=""fw-bold text-dark mb-2"">Chưa có sản phẩm nào trong giỏ hàng</h6>
                <p class=""text-muted mb-4"" style=""font-size: 14px;"">Cùng khám phá hàng ngàn sản phẩ");
            WriteLiteral("m công nghệ tại màn hình chính nhé!</p>\r\n                <a asp-controller=\"Product\" asp-action=\"Index\" class=\"btn cps-bg-red fw-bold px-4 py-2 rounded-3 text-decoration-none\">\r\n                    VỀ TRANG CHỦ\r\n                </a>\r\n            </div>\r\n");
#nullable restore
#line 150 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
        }

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n        <!-- Recommendations Section (CellphoneS style) -->\r\n");
#nullable restore
#line 153 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
         if (ViewBag.RecommendedProducts != null && ((List<ProductListVM>)ViewBag.RecommendedProducts).Any())
        {

#line default
#line hidden
#nullable disable
            WriteLiteral(@"            <div class=""mt-5 mb-5 pb-5"">
                <div class=""d-flex justify-content-between align-items-center mb-4"">
                    <h2 class=""cps-title mb-0"">Có thể bạn sẽ thích</h2>
                </div>
                <div class=""row row-cols-2 row-cols-md-3 row-cols-lg-4 g-3"">
");
#nullable restore
#line 160 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                     foreach (var item in (List<ProductListVM>)ViewBag.RecommendedProducts)
                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                        <div class=\"col\">\r\n                            <div class=\"pl-product-card h-100 shadow-sm border rounded-4 overflow-hidden\" style=\"background:#fff;\">\r\n                                <a");
            BeginWriteAttribute("href", " href=\"", 12455, "\"", 12505, 2);
            WriteAttributeValue("", 12462, "/product/", 12462, 9, true);
#nullable restore
#line 164 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 12471, item.Slug ?? item.Id.ToString(), 12471, 34, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" class=\"img-box d-block text-center p-3\" style=\"height:180px; background:#fff;\">\r\n                                    <img");
            BeginWriteAttribute("src", " src=\"", 12628, "\"", 12680, 1);
#nullable restore
#line 165 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 12634, item.ImageUrl ?? "/img/Product_Default.jpg", 12634, 46, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" class=\"img-fluid\" style=\"max-height:100%; object-fit:contain;\"");
            BeginWriteAttribute("alt", " alt=\"", 12744, "\"", 12760, 1);
#nullable restore
#line 165 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 12750, item.Name, 12750, 10, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" onerror=""this.src='/img/Product_Default.jpg'"">
                                </a>
                                <div class=""p-3 d-flex flex-column flex-grow-1"">
                                    <div class=""text-muted mb-1"" style=""font-size:11px;"">");
#nullable restore
#line 168 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                                     Write(item.BrandName ?? "Chính hãng");

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n                                    <a");
            BeginWriteAttribute("href", " href=\"", 13098, "\"", 13148, 2);
            WriteAttributeValue("", 13105, "/product/", 13105, 9, true);
#nullable restore
#line 169 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue("", 13114, item.Slug ?? item.Id.ToString(), 13114, 34, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" class=\"text-decoration-none text-dark fw-bold lh-sm mb-2\" style=\"font-size:14px; display:-webkit-box; -webkit-line-clamp:2; -webkit-box-orient:vertical; overflow:hidden; min-height:36px;\">");
#nullable restore
#line 169 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                                                                                                                                                                                                                                 Write(item.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</a>\r\n                                    \r\n                                    <div class=\"mt-auto\">\r\n                                        <div class=\"text-danger fw-bold fs-6 mb-2\">\r\n");
#nullable restore
#line 173 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                             if (item.Price > 0) {
                                                

#line default
#line hidden
#nullable disable
#nullable restore
#line 174 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                           Write(item.Price.ToString("N0"));

#line default
#line hidden
#nullable disable
            WriteLiteral("₫");
#nullable restore
#line 174 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                                        
                                            } else {
                                                

#line default
#line hidden
#nullable disable
            WriteLiteral("Liên hệ");
#nullable restore
#line 176 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                    
                                            }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"                                        </div>
                                        <div class=""d-flex align-items-center justify-content-between mt-1"">
                                            <div style=""color:#ffc107; font-size:11px; display:flex; align-items:center; gap:2px;"">
");
#nullable restore
#line 181 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                 for (int s = 1; s <= 5; s++) {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                                    <span>");
#nullable restore
#line 182 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                      Write(s <= Math.Round(item.AverageRating) ? "★" : "☆");

#line default
#line hidden
#nullable disable
            WriteLiteral("</span>\r\n");
#nullable restore
#line 183 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                                                <span class=\"text-muted ms-1\">");
#nullable restore
#line 184 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                                         Write(item.AverageRating.ToString("F1"));

#line default
#line hidden
#nullable disable
            WriteLiteral("</span>\r\n                                            </div>\r\n                                            <button type=\"button\" class=\"pl-wishlist-btn\"");
            BeginWriteAttribute("onclick", " onclick=\"", 14667, "\"", 14738, 6);
            WriteAttributeValue("", 14677, "toggleWishlist(event,", 14677, 21, true);
#nullable restore
#line 186 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue(" ", 14698, item.Id, 14699, 8, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 14707, ",", 14707, 1, true);
#nullable restore
#line 186 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
WriteAttributeValue(" ", 14708, item.VersionId ?? 0, 14709, 22, false);

#line default
#line hidden
#nullable disable
            WriteAttributeValue("", 14731, ",", 14731, 1, true);
            WriteAttributeValue(" ", 14732, "this)", 14733, 6, true);
            EndWriteAttribute();
            WriteLiteral(@" title=""Yêu thích"">
                                                <svg xmlns=""http://www.w3.org/2000/svg"" width=""16"" height=""16"" fill=""currentColor"" viewBox=""0 0 16 16"">
                                                    <path d=""M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748z""/>
                                                </svg>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
");
#nullable restore
#line 196 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                    }

#line default
#line hidden
#nullable disable
            WriteLiteral("                </div>\r\n            </div>\r\n");
#nullable restore
#line 199 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
        }

#line default
#line hidden
#nullable disable
            WriteLiteral("    </div>\r\n</div>\r\n\r\n");
#nullable restore
#line 203 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
Write(section);

#line default
#line hidden
#nullable disable
            WriteLiteral(" Scripts {\r\n<script>\r\n    // Cart item prices map\r\n    const itemPrices = {};\r\n");
#nullable restore
#line 207 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
     foreach (var item in (Model?.Items ?? new List<HDKmall.Models.CartItem>()))
    {
        var price = item.Variant != null ? item.Variant.Price : item.Product.Price;
        

#line default
#line hidden
#nullable disable
            WriteLiteral("itemPrices[");
#nullable restore
#line 210 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                    Write(item.Id);

#line default
#line hidden
#nullable disable
            WriteLiteral("] = ");
#nullable restore
#line 210 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                Write(price);

#line default
#line hidden
#nullable disable
            WriteLiteral(";");
#nullable restore
#line 210 "f:\thử nghiệm\PBL3-PhoneStoreMVC\HDKmall\Views\Cart\Index.cshtml"
                                                   
    }

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
    // Select All toggle
    const selectAllCb = document.getElementById('select-all');
    if (selectAllCb) {
        selectAllCb.addEventListener('change', function () {
            document.querySelectorAll('.item-checkbox').forEach(cb => cb.checked = this.checked);
            updateTotals();
        });
        document.querySelectorAll('.item-checkbox').forEach(cb => {
            cb.addEventListener('change', function () {
                const all = document.querySelectorAll('.item-checkbox');
                const checked = document.querySelectorAll('.item-checkbox:checked');
                selectAllCb.checked = all.length === checked.length;
                updateTotals();
            });
        });
    }

    function updateTotals() {
        const checked = document.querySelectorAll('.item-checkbox:checked');
        let total = 0;
        let totalQty = 0;
        checked.forEach(cb => {
            const itemId = parseInt(cb.value);
            const qtyInput = documen");
            WriteLiteral(@"t.getElementById('qty-' + itemId);
            const qty = qtyInput ? parseInt(qtyInput.value) : 1;
            total += (itemPrices[itemId] || 0) * qty;
            totalQty += qty;
        });
        document.getElementById('selected-count').textContent = checked.length;
        document.getElementById('selected-qty-text').textContent = '(' + totalQty + ' sản phẩm)';
        document.getElementById('total-amount').textContent = total.toLocaleString('vi-VN') + '₫';
    }

    function updateQty(itemId, newQty) {
        newQty = parseInt(newQty);
        if (isNaN(newQty) || newQty < 1) newQty = 1;

        const token = document.querySelector('input[name=""__RequestVerificationToken""]')?.value;
        fetch('/Cart/Update', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'X-Requested-With': 'XMLHttpRequest',
                'RequestVerificationToken': token || ''
            },
            body: '");
            WriteLiteral(@"cartItemId=' + itemId + '&quantity=' + newQty
        })
        .then(r => r.json())
        .then(data => {
            if (data.success) {
                const input = document.getElementById('qty-' + itemId);
                if (input) input.value = newQty;
                const subtotalEl = document.getElementById('subtotal-' + itemId);
                if (subtotalEl) {
                    const price = itemPrices[itemId] || 0;
                    subtotalEl.textContent = (price * newQty).toLocaleString('vi-VN') + '₫';
                }
                updateCartBadge(data.cartCount);
                updateTotals();
            }
        });
    }

    async function removeItem(itemId) {
        const confirmed = await modernConfirm('Xác nhận xóa?', 'Bạn có muốn xóa sản phẩm này khỏi giỏ hàng?');
        if (!confirmed) return;
        
        const token = document.querySelector('input[name=""__RequestVerificationToken""]')?.value;
        fetch('/Cart/Remove', {
            meth");
            WriteLiteral(@"od: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'X-Requested-With': 'XMLHttpRequest',
                'RequestVerificationToken': token || ''
            },
            body: 'cartItemId=' + itemId
        })
        .then(r => r.json())
        .then(data => {
            if (data.success) {
                showSuccessToast('Đã xóa sản phẩm khỏi giỏ hàng');
                const row = document.querySelector('.cart-item-row[data-item-id=""' + itemId + '""]');
                if (row) row.remove();
                delete itemPrices[itemId];
                updateCartBadge(data.cartCount);
                updateTotals();
                // If no items left, reload
                if (document.querySelectorAll('.cart-item-row').length === 0) {
                    setTimeout(() => location.reload(), 1000);
                }
            }
        });
    }

    function updateCartBadge(count) {
        const badge = doc");
            WriteLiteral(@"ument.getElementById('cart-badge');
        if (badge) {
            badge.textContent = count;
            badge.classList.toggle('d-none', count <= 0);
        }
    }

    // Mark wishlisted items on load (from server-side or global state)
    document.addEventListener('DOMContentLoaded', () => {
        updateTotals();
    });
</script>
}

");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
