#pragma checksum "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1394101a9b85341c86e907573edf12fbbf7d7d57"
// <auto-generated/>
#pragma warning disable 1591
namespace Razor
{
    #line hidden
#nullable restore
#line 1 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\_ViewImports.cshtml"
using HDKmall;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\_ViewImports.cshtml"
using HDKmall.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\_ViewImports.cshtml"
using HDKmall.ViewModels;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\_ViewImports.cshtml"
using HDKmall.Helpers;

#line default
#line hidden
#nullable disable
    public class Template
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 1 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
Write(model);

#line default
#line hidden
#nullable disable
            WriteLiteral(" HDKmall.ViewModels.ProfileVM\r\n");
#nullable restore
#line 2 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
  
    ViewData["Title"] = "Hồ sơ cá nhân";

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
<div class=""container"" style=""padding-top:40px;padding-bottom:60px;max-width:900px"">
    <div class=""breadcrumb"" style=""margin-bottom:24px"">
        <a href=""/"">Trang chủ</a>
        <span class=""breadcrumb-sep"">›</span>
        <span>Hồ sơ</span>
    </div>

");
#nullable restore
#line 13 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
     if (TempData["SuccessMessage"] != null)
    {

#line default
#line hidden
#nullable disable
            WriteLiteral("        <div class=\"alert alert-success\">");
#nullable restore
#line 15 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                                    Write(TempData["SuccessMessage"]);

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n");
#nullable restore
#line 16 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
    }

#line default
#line hidden
#nullable disable
#nullable restore
#line 17 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
     if (TempData["ErrorMessage"] != null)
    {

#line default
#line hidden
#nullable disable
            WriteLiteral("        <div class=\"alert alert-danger\">");
#nullable restore
#line 19 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                                   Write(TempData["ErrorMessage"]);

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n");
#nullable restore
#line 20 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
    }

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n    <div class=\"row g-4\">\r\n        <div class=\"col-md-6\">\r\n            <div class=\"card p-3\">\r\n                <h5 class=\"mb-3\">Thông tin tài khoản</h5>\r\n                <form asp-action=\"Profile\" method=\"post\">\r\n                    ");
#nullable restore
#line 27 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
               Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                    <div asp-validation-summary=""ModelOnly"" class=""text-danger mb-2""></div>
                    <div class=""mb-3"">
                        <label asp-for=""FullName"" class=""form-label""></label>
                        <input asp-for=""FullName"" class=""form-control"" />
                        <span asp-validation-for=""FullName"" class=""text-danger""></span>
                    </div>
                    <div class=""mb-3"">
                        <label asp-for=""Email"" class=""form-label""></label>
                        <input asp-for=""Email"" class=""form-control"" readonly />
                    </div>
                    <div class=""mb-3"">
                        <label asp-for=""PhoneNumber"" class=""form-label""></label>
                        <input asp-for=""PhoneNumber"" class=""form-control"" />
                        <span asp-validation-for=""PhoneNumber"" class=""text-danger""></span>
                    </div>
                    <button type=""submit"" class=""btn btn-primary"">Cập nhậ");
            WriteLiteral(@"t hồ sơ</button>
                </form>
            </div>
        </div>

        <div class=""col-md-6"">
            <div class=""card p-3"">
                <h5 class=""mb-3"">Đổi mật khẩu</h5>
                <form asp-action=""ChangePassword"" method=""post"">
                    ");
#nullable restore
#line 52 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
               Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                    <div class=""mb-3"">
                        <label class=""form-label"">Mật khẩu hiện tại</label>
                        <input asp-for=""CurrentPassword"" type=""password"" class=""form-control"" />
                    </div>
                    <div class=""mb-3"">
                        <label class=""form-label"">Mật khẩu mới</label>
                        <input asp-for=""NewPassword"" type=""password"" class=""form-control"" />
                    </div>
                    <div class=""mb-3"">
                        <label class=""form-label"">Xác nhận mật khẩu mới</label>
                        <input asp-for=""ConfirmNewPassword"" type=""password"" class=""form-control"" />
                    </div>
                    <button type=""submit"" class=""btn btn-warning"">Đổi mật khẩu</button>
                </form>
            </div>
        </div>
    </div>

");
#nullable restore
#line 71 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
     if (!User.IsInRole("Admin"))
    {

#line default
#line hidden
#nullable disable
            WriteLiteral("        <div class=\"card p-3 mt-4\">\r\n            <h5 class=\"mb-3\">Quản lý địa chỉ giao hàng</h5>\r\n            <form asp-action=\"AddAddress\" method=\"post\" class=\"row g-3\">\r\n                ");
#nullable restore
#line 76 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
           Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
                <div class=""col-md-4"">
                    <input asp-for=""NewAddressRecipientName"" class=""form-control"" placeholder=""Người nhận"" />
                </div>
                <div class=""col-md-3"">
                    <input asp-for=""NewAddressPhoneNumber"" class=""form-control"" placeholder=""Số điện thoại"" />
                </div>
                <div class=""col-md-5"">
                    <input asp-for=""NewAddressLine"" class=""form-control"" placeholder=""Địa chỉ cụ thể"" />
                </div>
                <div class=""col-12"">
                    <label class=""form-check"">
                        <input asp-for=""SetAsDefaultAddress"" class=""form-check-input"" />
                        <span class=""form-check-label"">Đặt làm địa chỉ mặc định</span>
                    </label>
                </div>
                <div class=""col-12"">
                    <button type=""submit"" class=""btn btn-success"">Thêm địa chỉ</button>
                </div>
            </form>

         ");
            WriteLiteral("   <hr />\r\n");
#nullable restore
#line 98 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
             if (Model.Addresses.Any())
            {

#line default
#line hidden
#nullable disable
            WriteLiteral("                <div class=\"list-group\">\r\n");
#nullable restore
#line 101 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                     foreach (var address in Model.Addresses)
                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                        <div class=\"list-group-item d-flex justify-content-between align-items-center gap-2\">\r\n                            <div>\r\n                                <strong>");
#nullable restore
#line 105 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                                   Write(address.RecipientName);

#line default
#line hidden
#nullable disable
            WriteLiteral("</strong> - ");
#nullable restore
#line 105 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                                                                     Write(address.PhoneNumber);

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                <div>");
#nullable restore
#line 106 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                                Write(address.AddressLine);

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n");
#nullable restore
#line 107 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                                 if (address.IsDefault)
                                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                    <span class=\"badge bg-primary mt-1\">Mặc định</span>\r\n");
#nullable restore
#line 110 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                            </div>\r\n                            <div class=\"d-flex gap-2\">\r\n");
#nullable restore
#line 113 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                                 if (!address.IsDefault)
                                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                                    <form asp-action=\"SetDefaultAddress\" method=\"post\">\r\n                                        ");
#nullable restore
#line 116 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                                   Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                        <input type=\"hidden\" name=\"addressId\"");
            BeginWriteAttribute("value", " value=\"", 5522, "\"", 5548, 1);
#nullable restore
#line 117 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
WriteAttributeValue("", 5530, address.AddressId, 5530, 18, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" />\r\n                                        <button type=\"submit\" class=\"btn btn-outline-primary btn-sm\">Đặt mặc định</button>\r\n                                    </form>\r\n");
#nullable restore
#line 120 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                                }

#line default
#line hidden
#nullable disable
            WriteLiteral("                                <form asp-action=\"DeleteAddress\" method=\"post\" onsubmit=\"confirmDeleteAddress(event, this);\">\r\n                                    ");
#nullable restore
#line 122 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                               Write(Html.AntiForgeryToken());

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                                    <input type=\"hidden\" name=\"addressId\"");
            BeginWriteAttribute("value", " value=\"", 6020, "\"", 6046, 1);
#nullable restore
#line 123 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
WriteAttributeValue("", 6028, address.AddressId, 6028, 18, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(@" />
                                    <button type=""button"" class=""btn btn-outline-danger btn-sm"" onclick=""confirmDeleteAddress(event, this.closest('form'));"">Xóa</button>
                                </form>
                            </div>
                        </div>
");
#nullable restore
#line 128 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
                    }

#line default
#line hidden
#nullable disable
            WriteLiteral("                </div>\r\n");
#nullable restore
#line 130 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
            }
            else
            {

#line default
#line hidden
#nullable disable
            WriteLiteral("                <p class=\"text-muted mb-0\">Bạn chưa có địa chỉ giao hàng nào.</p>\r\n");
#nullable restore
#line 134 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
            }

#line default
#line hidden
#nullable disable
            WriteLiteral("        </div>\r\n");
#nullable restore
#line 136 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
    }

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>\r\n\r\n");
#nullable restore
#line 139 "f:\pbl3\PBL3-PhoneStoreMVC\HDKmall\Views\Account\Profile.cshtml"
Write(section);

#line default
#line hidden
#nullable disable
            WriteLiteral(@" Scripts {
    <partial name=""_ValidationScriptsPartial"" />
    <script>
        async function confirmDeleteAddress(event, form) {
            event.preventDefault();
            const confirmed = await modernConfirm('Xác nhận xóa?', 'Bạn có chắc chắn muốn xóa địa chỉ này?');
            if (confirmed) {
                form.submit();
            }
        }
    </script>
}");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
